{
  "hash": "16c0160aa02901b6e6a713af8dfcf094",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Zero-Inflated Models: A Practical Tutorial\"\ndescription: \"A practical guide to understanding and implementing zero-inflated models in R.\"\nimage: publication-image.png\nimage-alt: \"Two paths converge into observed count data: one produces structural zeros, while the other produces counts that can also include zeros.\"\ntitle-block-banner: publication-image.png\nopen-graph: true\ntwitter-card:\n  card-style: summary_large_image\nauthor: \"Andrea Di Francia\"\ndate: \"2026-06-15\"\ncategories: [statistics, modeling, R, tutorial]\nbibliography: references.bib\nexecute:\n  echo: true\n  warning: false\n  message: false\ncode-annotations: below\nformat:\n  html:\n    toc-depth: 3\n    number-sections: true\n    number-depth: 3\n    code-copy: true\n    code-overflow: wrap\n    fig-align: center\n    fig-cap-location: bottom\n    tbl-cap-location: top\n---\n\n\n\n```{=html}\n<style>\n.quarto-title-banner {\n  background-color: rgba(6, 18, 34, 0.62);\n  background-blend-mode: multiply;\n  background-position: center;\n  background-repeat: no-repeat;\n}\n\n/* Keep long equations inside the article column on narrow screens. MathJax\n   containers are keyboard-focusable, so readers can scroll them directly. */\nmjx-container[display=\"true\"] {\n  display: block;\n  max-width: 100%;\n  overflow-x: auto;\n  overflow-y: hidden;\n  padding-bottom: 0.25rem;\n}\n\n</style>\n```\n\n# Introduction\n\nIn the past couple of years, I have worked with many healthcare datasets containing large numbers of zero outcomes. This problem is not unique to healthcare, but it can make standard count models difficult to apply. Zero-inflated models offer one flexible way to represent those data.\n\nThat flexibility also makes these models harder to implement and interpret. They receive less attention than many machine-learning methods, so I initially found it difficult to locate practical guidance that connected the theory, code, diagnostics, and interpretation.\n\nThis post grew out of the notes I made while applying zero-inflated models in industry, plus some of the internal training sessions I later ran on the topic. My goal is to provide a practical, hands-on guide to understanding and implementing zero-inflated models. There is some theory involved, but no background on this topic is necessary: the article builds up from ordinary count regression before introducing the two-process model.\n\nThis tutorial covers the theoretical foundations, practical implementation, model comparison, diagnostics, and interpretation of some of the simpler and more common zero-inflated count models. A follow-up tutorial may examine hurdle models, alternative count distributions, and more advanced validation strategies.\n\nIn terms of tooling, I strongly recommend the `glmmTMB` package in R, which is flexible, widely adopted, and well suited to the generalized linear model extensions used here. The Python ecosystem for this task is not quite as mature yet, although for standard applications the `statsmodels` library is a good starting point. The modelling sequence in this tutorial is simple enough and should be easily transferable if you decide to take that approach.\n\n## What Are Zero-Inflated Models?\n\nIn regression, zero-inflated models combine two components: a point mass at zero, which produces only zero—a component that produces only zeros—and a second distribution for the outcome. Predictors can enter both components through separate linear predictors and link functions. In this sense, zero-inflated regression models are technically defined as generalized linear mixture models.\n\nAlthough they are often introduced for count data, the general framework is not limited to counts. For example, @liu2019 review zero-inflated models for non-negative continuous outcomes, while @ospina2012 develop zero-or-one-inflated beta regression for proportions.\n\nThis tutorial focuses on count data, where an observed count can arise from two distinct latent processes:\n\n1. One that generates **structural zeros** with some probability.\n2. A standard event-generating process that produces both zeros (called **sampling zeros**) and positive events.\n\nWhat does this actually mean? Well, suppose you are counting clinic visits. A zero can mean at least two different things:\n\n- the person was never really in a position to generate a visit during the study window\n- the person could have generated a visit, but happened not to\n\nThe first type is a **structural zero**. The second is a **sampling zero**. A standard one-process count model, such as Poisson regression, treats both people as coming from the same count-generating process. A zero-inflated model represents both routes to zero, although it cannot tell us with certainty which route produced any individual observation.\n\n## When Do We Need Zero-Inflated Models?\n\nThe key challenge zero-inflated models try to address is **excess zeros** in the data. However, the useful question is not \"does my dataset contain a lot of zeros?\", but **do the zeros plausibly come from more than one process?**\n\nThis distinction will become clearer in the following sections, but for now these are some helpful examples to keep in mind:\n\n- **Healthcare use**: Some patients are effectively unable to generate events because they never access services (structural zeros)—for example, people living in remote areas with no nearby clinics, or those excluded by policy or eligibility criteria. Other patients could use services but happen not to during the study window (sampling zeros)—for example, healthy patients who simply do not visit in that period or patients whose condition does not require care.\n- **Disease surveillance**: Some locations truly have zero prevalence for a pathogen because the pathogen cannot survive there or has been eradicated (structural zeros). Other locations harbor the pathogen but a given survey fails to detect it during that sampling round (sampling zeros) — e.g., low prevalence or imperfect tests.\n- **Specialist treatments or prescriptions**: Some patients will never be eligible for a specific specialist-only procedure or advanced drug (structural zeros) — think of treatments restricted by age, comorbidity, or insurance coverage. Other patients are eligible but simply don't receive the treatment during the study window (sampling zeros) because they don't yet need it, they defer care, or the treatment is rarely used in short follow-up.\n\n![In healthcare data, zeros can come from fundamentally different processes: policy or access barriers create structural zeros, while ordinary non-use during the observation window creates sampling zeros.](zero-sources.svg){#fig-zero-sources fig-alt=\"A hand-drawn flow diagram splitting healthcare count zeros into structural zeros from access or eligibility barriers and sampling zeros from no care needed or non-attendance.\"}\n\nIn each case, the zero may carry information about the process that generated the observation. That still leaves an important modelling caveat: excess zeros are not the same thing as proven structural zeros. A flexible one-process count model can sometimes reproduce many zeros without needing a separate latent class.\n\n# Theoretical Foundation: From GLMs to  Mixture Models\n\n## Generalized Linear Models\n\nBefore fitting zero-inflated models, it helps to revisit **generalized linear models** (GLMs). Counts are non-negative integers, usually right-skewed, and often have variance that changes with the mean. Ordinary linear regression does not encode those features: it can predict negative values and assumes a constant-variance normal error structure. GLMs allow us to retain a regression-style mean model while using a response distribution suited to the outcome.\n\nA GLM connects a linear predictor to the mean of an outcome distribution through a link function. Three ingredients define that structure:\n\n1. **Linear predictor** ($\\eta_i=X_i\\beta$): a linear combination of predictor values and coefficients\n2. **Link function** ($g(\\mu_i)=\\eta_i$): the transformation connecting the linear predictor to the conditional mean\n3. **Response distribution**: a distribution suited to the outcome, such as Bernoulli for a binary response or Poisson for a count\n\n![A generalized linear model turns predictors into a linear predictor, transforms it through a link function, and uses the result as the expected value for an observation model.](glm-pipeline.png){#fig-glm-pipeline fig-alt=\"A hand-drawn left-to-right pipeline: predictors, linear predictor, link function, expected response, and observed outcome distribution.\"}\n\nZero-inflated count models use this structure twice: a binary component models membership in the latent extra-zero group, and a count component models the expected outcome among observations in the count-generating group. The original zero-inflated Poisson regression paper framed this as a practical way to model excess zeros in manufacturing defects [@lambert1992]; the same idea now appears across health, ecology, insurance, and many other settings.\n<!-- Review paragraph below, need to sound more editorial -->\nLogistic and Poisson regression provide the two building blocks. A short exponential-family refresher first recovers the logit link for a Bernoulli response; the following count-model section then applies the same logic to Poisson regression and its extensions.\n\n## The Exponential Family\n\nThe **exponential family** is a collection of probability distributions with a shared mathematical form. This might sound abstract, but it includes most distributions you encounter in practice: normal, Poisson, binomial, gamma, and many others.\n\nA density or probability mass function in this family can be written as:\n\n$$f(y\\mid\\theta, \\phi) = \\exp\\left\\{\\frac{y\\theta-b(\\theta)}{a(\\phi)} + c(y,\\phi)\\right\\}.$$\n\nThe notation separates the parts that govern the distribution:\n\n- $\\theta$ is the **natural parameter**;\n- $\\phi$ is a **dispersion parameter**, with $a(\\phi)$ controlling its scale;\n- $b(\\theta)$ determines the mean and variance through its first two derivatives;\n- $c(y,\\phi)$ supplies the remaining terms needed to define a valid distribution.\n\nEven though the formula looks daunting, the important part to keep in mind is that this format essentially *standardises* how we work with different distributions. In particular, it can be proved that for all distributions in this family, the mean and variance are:\n\n$$E(Y)=b'(\\theta), \\qquad \\operatorname{Var}(Y)=a(\\phi)b''(\\theta).$$\n\nThis common structure is what allows GLMs to pair different response distributions with a linear predictor. For a fuller treatment, McCullagh and Nelder give the classic mathematical account, while Dobson and Barnett provide a more introductory route through the same material [@mccullagh1989; @dobson2018].\n\n### The Bernoulli Distribution\n\nFor a Bernoulli outcome $Y\\in\\{0,1\\}$ with success probability $p$,\n\n$$f(y\\mid p) = p^y(1-p)^{1-y}\n= \\exp\\left\\{y\\log\\left(\\frac{p}{1-p}\\right)+\\log(1-p)\\right\\}.$$\n\nWriting the mass function this way identifies the natural parameter as\n\n$$\\theta=\\log\\left(\\frac{p}{1-p}\\right),$$\n\nalso known as the logit of $p$. Bernoulli regression therefore uses the canonical logit link:\n\n$$\\operatorname{logit}(p_i)=\\log\\left(\\frac{p_i}{1-p_i}\\right)=X_i\\beta.$$\n\nThe linear predictor $X_i\\beta$ can take any real value, while the inverse-logit transformation keeps $p_i$ between 0 and 1. \n\nExponentiating a coefficient gives an odds ratio: $e^{\\beta_j}$ is the multiplicative change in the odds for a one-unit increase in $x_j$, holding the other predictors fixed. For example, if $\\beta_j=0.20$, then $e^{0.20}=1.22$, corresponding to a 22% higher odds for a one-unit increase in $x_j$. We will later use this same link to model the probability of latent extra-zero membership.\n\nChanging the response distribution changes the canonical link and the variance assumption, but not the basic GLM architecture. We now make that transition from a binary response to a count response.\n\n## Count-Model Building Blocks\n\nPoisson regression is the count-data counterpart to the Bernoulli example above: its exponential-family form produces a log link, while its response distribution supplies the mean-variance relationship. That separation matters because the link and the variance assumption can succeed or fail for different reasons.\n\nThe models therefore follow a deliberate sequence. We start with Poisson regression, check its conditional variance and zero predictions, move to negative binomial regression when the count process is overdispersed, and only then ask whether a separate zero-inflation process remains useful. Each step preserves the regression-style mean model while relaxing a specific distributional restriction.\n\n### Poisson Regression\n\nPoisson regression is usually the standard first model for a count outcome. For person $i$, it assumes\n\n$$Y_i \\mid X_i \\sim \\operatorname{Poisson}(\\lambda_i), \\qquad \\log(\\lambda_i) = X_i\\beta.$$\n\nIts probability mass function has the exponential-family form\n\n$$P(Y_i=y\\mid X_i)=\\frac{\\lambda_i^y e^{-\\lambda_i}}{y!}\n=\\exp\\left\\{y\\log(\\lambda_i)-\\lambda_i-\\log(y!)\\right\\}.$$\n\nThe natural parameter is therefore $\\theta_i=\\log(\\lambda_i)$, with $b(\\theta_i)=e^{\\theta_i}=\\lambda_i$. The canonical log link keeps the expected count $\\lambda_i$ positive. Exponentiating a regression coefficient gives a rate ratio: if $\\beta_j=0.20$, then $e^{0.20}=1.22$, corresponding to a 22% higher expected count for a one-unit increase in $x_j$, holding the other predictors fixed. Notice the interpretation is different from the odds ratio in the Bernoulli case: ...\n\nThe Poisson distribution has no estimated dispersion parameter, so $a(\\phi)=1$ in the general exponential-family form. Its derivative relationships are therefore\n\n$$\na(\\phi)=1,\n\\qquad\nb'(\\theta_i)=b''(\\theta_i)=e^{\\theta_i}=\\lambda_i,\n$$\n\nand hence the Poisson mean--variance relationship\n\n$$\nE(Y_i \\mid X_i)=\\operatorname{Var}(Y_i \\mid X_i)=\\lambda_i.\n$$\n\nThis equality applies after conditioning on the predictors. Across the sample, people can have different values of $\\lambda_i$, so combining their count distributions can produce a raw variance larger than the raw mean even when the conditional Poisson assumption holds. A large variance-to-mean ratio or a large number of zeros is therefore a warning, not evidence by itself of either conditional overdispersion or a separate zero-generating process. We assess those possibilities after fitting the Poisson mean model.\n\n### Overdispersion and Negative Binomial Distribution\n\nRelative to a Poisson model, **conditional overdispersion** means\n\n$$\n\\operatorname{Var}(Y_i\\mid X_i)>E(Y_i\\mid X_i).\n$$\n\nAt a given conditional mean, an overdispersed count distribution is more spread out than the corresponding Poisson distribution. It places less probability near the mean and more in the tails, including at zero and at unusually large counts. An overdispersed one-process distribution can therefore reproduce zeros that a Poisson model misses without introducing a separate extra-zero group. Unobserved differences between people, an incomplete mean model, or dependence between observations can all produce this pattern. Whatever its source, unmodelled overdispersion makes Poisson standard errors too small and may leave too little fitted probability in both the lower and upper tails.\n\nThe negative binomial distribution tries to address this by adding an extra dispersion parameter. It allows us to keep the same log mean model,\n\n$$\\log(\\mu_i) = X_i\\beta,$$\n\nbut relaxes the Poisson variance assumption. `glmmTMB` provides two common negative-binomial parameterizations:\n\n$$\n\\begin{aligned}\n\\texttt{nbinom1}:\\quad\n  \\operatorname{Var}(Y_i\\mid X_i) &= \\mu_i(1+\\alpha), \\\\\n\\texttt{nbinom2}:\\quad\n  \\operatorname{Var}(Y_i\\mid X_i) &= \\mu_i+\\frac{\\mu_i^2}{\\phi}.\n\\end{aligned}\n$$\n\nIn `nbinom1`, the additional variance $\\alpha\\mu_i$ grows linearly with the mean, and the Poisson limit occurs as $\\alpha\\to0$. In `nbinom2`, the additional variance $\\mu_i^2/\\phi$ grows quadratically, and the Poisson limit occurs as $\\phi\\to\\infty$. The models fitted below use NB2 because its variance permits progressively greater spread at higher expected visit counts and because the zero-inflated negative binomial count component uses the same distribution. NB1 would remain plausible if the extra conditional variance increased approximately linearly with the mean.\n\nNB2 also has a useful interpretation in terms of unobserved heterogeneity. Suppose counts are Poisson conditional on an individual event rate, but those rates vary according to a gamma distribution among people with the same observed predictors. Integrating over that variation gives the NB2 distribution, with $\\mu_i^2/\\phi$ measuring the additional variance due to differences in the underlying rates.\n\n::: {.callout-caution collapse=\"true\"}\n## Mathematical details: NB2 in exponential-family form\n\nFor NB2, the conditional probability mass function is\n\n$$\nP(Y_i=y\\mid X_i)\n=\\frac{\\Gamma(y+\\phi)}{\\Gamma(\\phi)y!}\n \\left(\\frac{\\phi}{\\phi+\\mu_i}\\right)^\\phi\n \\left(\\frac{\\mu_i}{\\phi+\\mu_i}\\right)^y,\n\\qquad y=0,1,2,\\ldots.\n$$\n\nFor fixed $\\phi$, we can define\n\n$$\n\\theta_i=\\log\\left(\\frac{\\mu_i}{\\mu_i+\\phi}\\right),\n\\qquad\nb(\\theta_i)=-\\phi\\log(1-e^{\\theta_i}).\n$$\n\nThe mass function can then be written in exponential-family form as\n\n$$\nP(Y_i=y\\mid X_i)\n=\\exp\\left\\{\n  y\\theta_i-b(\\theta_i)\n  +\\log\\Gamma(y+\\phi)-\\log\\Gamma(\\phi)-\\log(y!)\n\\right\\}.\n$$\n\nDifferentiating $b(\\theta_i)$ recovers the NB2 conditional moments:\n\n$$\nE(Y_i\\mid X_i)=b'(\\theta_i)=\\mu_i,\n\\qquad\n\\operatorname{Var}(Y_i\\mid X_i)=b''(\\theta_i)\n=\\mu_i+\\frac{\\mu_i^2}{\\phi}.\n$$\n\n:::\n\nBecause NB2 assigns more probability to zero than a Poisson distribution with the same mean, it may account for some of an observed zero surplus without a separate structural-zero process. The case study therefore fits NB2 as the stronger one-process baseline before introducing a separate extra-zero mechanism.\n\n::: {.callout-note collapse=\"true\"}\n## Generalized Poisson models\n\nPoisson and negative binomial models are not the only count-process choices. A generalized Poisson model is another way to relax the Poisson mean-variance relationship. In a common parameterization, let $\\delta$ control dispersion and define\n\n$$D = \\frac{1}{(1-\\delta)^2}.$$\n\nFor conditional mean $\\mu_i$, the variance is then\n\n$$\\operatorname{Var}(Y_i \\mid X_i) = \\mu_iD = \\frac{\\mu_i}{(1-\\delta)^2}.$$\n\nThe ordinary Poisson model is recovered when $\\delta=0$ and $D=1$. Positive $\\delta$ gives $D>1$ and overdispersion; negative $\\delta$ gives $D<1$ and underdispersion, subject to the admissible parameter range. In `glmmTMB`'s `genpois` family, the same variance is written as $\\operatorname{Var}(Y_i\\mid X_i)=\\mu_i\\phi_{\\mathrm{GP}}^2$. Thus $\\phi_{\\mathrm{GP}}^2$ is the index of dispersion—the same quantity denoted by $D$ above.\n\nThis mean-variance pattern differs from `nbinom2`. Generalized Poisson variance is proportional to $\\mu_i$ through $D$, whereas `nbinom2` adds the quadratic term $\\mu_i^2/\\phi$. I do not fit a generalized Poisson model here because the tutorial focuses on ZIP and ZINB, but it is a useful nearby option when the negative binomial variance pattern is a poor match.\n:::\n\n# Data, Exploration, and Baseline Models\n\nSection 2 established the three main modelling possibilities carried into the case study: Poisson variation as a baseline, additional variation within a negative binomial count process, and a separate extra-zero process that can be combined with either count distribution. We now take those possibilities to the Medicare data. In general, it is good practice to progressively establish how and where more flexible one-process models fail, before implementing a two-process model.\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" title=\"Prerequisites\"}\n\nInstall the required packages before running the analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install packages if not already available\ninstall.packages(c(\n  \"glmmTMB\", \"DHARMa\", \"performance\", \"parameters\", \"ggplot2\", \"dplyr\",\n  \"gridExtra\", \"knitr\", \"catdata\"\n))\n```\n:::\n\n:::\n\n## Medicare Data and Outcome\n\nThe `medcare` dataset from the `catdata` package records healthcare use for 4,406 people aged 66 and over who were covered by Medicare. The outcome, `ofp`, is each person's number of physician office visits during the observation period.\n\nI like this example because the case for a zero-inflated model is not obvious from one dramatic spike at zero. The data instead make us work through the same questions that arise in practice: how variable are the counts, which patients have no visits, and can a standard count model reproduce the observed zeros?\n\nThe analysis uses the following packages and variables:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show package-loading code\"}\n# Load required packages\nlibrary(glmmTMB)\nlibrary(DHARMa)\nlibrary(performance)\nlibrary(parameters)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(catdata)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show data-loading code\"}\n# Load the medical care dataset\ndata(medcare)\n\n# Examine the structure of the data\nhead(medcare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ofp hosp healthpoor healthexcellent numchron male age married school\n1   5    1          0               0        2    1 6.9       1      6\n2   1    0          0               0        2    0 7.4       1     10\n3  13    3          1               0        4    0 6.6       0     10\n4  16    1          1               0        2    1 7.6       1      3\n5   3    0          0               0        2    0 7.9       1      6\n6  17    0          1               0        5    0 6.6       0      7\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show data-loading code\"}\nglimpse(medcare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4,406\nColumns: 9\n$ ofp             <int> 5, 1, 13, 16, 3, 17, 9, 3, 1, 0, 0, 44, 2, 1, 19, 19, …\n$ hosp            <int> 1, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, …\n$ healthpoor      <int> 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, …\n$ healthexcellent <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ numchron        <int> 2, 2, 4, 2, 2, 5, 0, 0, 0, 0, 1, 5, 1, 1, 1, 0, 1, 2, …\n$ male            <int> 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, …\n$ age             <dbl> 6.9, 7.4, 6.6, 7.6, 7.9, 6.6, 7.5, 8.7, 7.3, 7.8, 6.6,…\n$ married         <int> 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, …\n$ school          <int> 6, 10, 10, 3, 6, 7, 8, 8, 8, 8, 8, 15, 8, 8, 12, 8, 8,…\n```\n\n\n:::\n:::\n\n\nThe variables used in this section are:\n\n- `ofp`: Number of physician office visits (our count outcome)\n- `healthpoor`: Individual has poor health (reference: average health)\n- `healthexcellent`: Individual has excellent health\n- `numchron`: Number of chronic conditions\n- `male`: Gender (female = 0, male = 1)\n- `age`: Age in decades (`6.6` represents 66 years)\n- `married`: Marital status (married = 1, else = 0)\n\n## Distribution of Visits and Observed Zeros\n\nThe outcome summary keeps the sample size, centre, spread, and frequency of zeros in one place.\n\n\n::: {#tbl-doctor-visit-summary .cell tbl-cap='Distribution of physician office visits (`ofp`).'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show summary table code\"}\nstats_tbl <- tibble::tibble(\n  Metric = c(\n    \"Participants\",\n    \"Zero-visit records\",\n    \"Proportion with zero visits\",\n    \"Median visits\",\n    \"Mean visits\",\n    \"Variance\",\n    \"Variance-to-mean ratio\",\n    \"Maximum visits\"\n  ),\n  Value = c(\n    format(nrow(medcare), big.mark = \",\"),\n    format(sum(medcare$ofp == 0), big.mark = \",\"),\n    sprintf(\"%.1f%%\", 100 * mean(medcare$ofp == 0)),\n    sprintf(\"%.0f\", median(medcare$ofp)),\n    sprintf(\"%.2f\", mean(medcare$ofp)),\n    sprintf(\"%.2f\", var(medcare$ofp)),\n    sprintf(\"%.2f\", var(medcare$ofp) / mean(medcare$ofp)),\n    sprintf(\"%.0f\", max(medcare$ofp))\n  )\n)\n\nknitr::kable(stats_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|Metric                      |Value |\n|:---------------------------|:-----|\n|Participants                |4,406 |\n|Zero-visit records          |683   |\n|Proportion with zero visits |15.5% |\n|Median visits               |4     |\n|Mean visits                 |5.77  |\n|Variance                    |45.69 |\n|Variance-to-mean ratio      |7.91  |\n|Maximum visits              |89    |\n\n\n:::\n:::\n\n\nThere are three key insights we can draw from @tbl-doctor-visit-summary:\n\n- 683 people (15.5%) have no recorded visits, and zero is the most frequent single count. That is a noticeable concentration, but its size alone does not establish zero-inflation. A Poisson or negative binomial distribution can also generate zeros.\n\n- The outcome is considerably right-skewed: the median is four visits, the mean is 5.77, and the maximum is 89 visits.\n\n- The variance is 7.91 times the mean. This **marginal** variance-to-mean ratio warns us that a Poisson model may be too restrictive, although the relevant assumption is conditional equidispersion after accounting for the predictors. We will test that on the fitted model rather than declaring overdispersion from the raw outcome alone.\n\n### Zero Patterns Across Patient Characteristics\n\nBy exploring the distribution of zero-visit records, we notice that they are not distributed uniformly across the observed patient characteristics.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show visualization code\"}\np1 <- ggplot(medcare, aes(x = ofp)) +\n  geom_histogram(\n    binwidth = 1,\n    boundary = -0.5,\n    fill = \"#4C78A8\",\n    color = \"white\"\n  ) +\n  coord_cartesian(xlim = c(-0.5, 20.5)) +\n  labs(\n    title = \"Most participants recorded relatively few visits\",\n    x = \"Physician office visits\",\n    y = \"Participants\"\n  ) +\n  theme_minimal() +\n  theme(plot.title = element_text(face = \"bold\"))\n\nhealth_zeros <- medcare |>\n  mutate(health_status = case_when(\n    healthpoor == 1 ~ \"Poor\",\n    healthexcellent == 1 ~ \"Excellent\",\n    TRUE ~ \"Average\"\n  )) |>\n  mutate(\n    health_status = factor(\n      health_status,\n      levels = c(\"Poor\", \"Average\", \"Excellent\")\n    )\n  ) |>\n  group_by(health_status) |>\n  summarise(prop_zeros = mean(ofp == 0), .groups = \"drop\")\n\np2 <- health_zeros |>\n  ggplot(aes(x = health_status, y = prop_zeros)) +\n  geom_col(fill = \"#F58518\", width = 0.7) +\n  scale_y_continuous(\n    labels = function(x) paste0(round(100 * x), \"%\"),\n    limits = c(0, 0.27)\n  ) +\n  labs(\n    title = \"Zeros vary by reported health\",\n    x = \"Self-reported health\",\n    y = \"Zero-visit records\"\n  ) +\n  theme_minimal() +\n  theme(plot.title = element_text(face = \"bold\"))\n\nchronic_zeros <- medcare |>\n  group_by(numchron) |>\n  summarise(\n    prop_zeros = mean(ofp == 0),\n    participants = n(),\n    .groups = \"drop\"\n  ) |>\n  filter(participants >= 20)\n\np3 <- chronic_zeros |>\n  ggplot(aes(x = numchron, y = prop_zeros)) +\n  geom_col(fill = \"#54A24B\", width = 0.75) +\n  scale_x_continuous(breaks = chronic_zeros$numchron) +\n  scale_y_continuous(\n    labels = function(x) paste0(round(100 * x), \"%\"),\n    limits = c(0, 0.32)\n  ) +\n  labs(\n    title = \"Zeros fall as chronic conditions increase\",\n    x = \"Chronic conditions\",\n    y = \"Zero-visit records\"\n  ) +\n  theme_minimal() +\n  theme(plot.title = element_text(face = \"bold\"))\n\ngridExtra::grid.arrange(\n  p1,\n  p2,\n  p3,\n  layout_matrix = rbind(c(1, 1), c(2, 3))\n)\n```\n\n::: {.cell-output-display}\n![Physician office visits and the distribution of zero-visit records across patient characteristics. The histogram is zoomed to 0–20 visits; 3.0% of observations lie above this range.](index_files/figure-html/fig-zero-inflation-eda-1.png){#fig-zero-inflation-eda fig-alt='A three-panel figure. The top panel shows a right-skewed histogram of office visits with zero as the most common count. The lower panels show that zero visits are most common among people reporting excellent health and become less common as the number of chronic conditions increases.' width=960}\n:::\n:::\n\n\nThe descriptive pattern is clearest for chronic conditions. About 29% of people with no chronic conditions recorded zero visits, compared with 9% of those with two conditions and 6% of those with three. The final bars are based on smaller groups, so the overall decline matters more than every local change.\n\nSelf-reported health shows a less linear pattern. The zero proportion is highest for people reporting excellent health (24%), followed by average health (15%) and poor health (11%). These are unadjusted comparisons: age, sex, marital status, and chronic conditions differ between the groups. We therefore cannot read the bars as isolated health-status effects, still less as evidence that any particular zero is structural.\n\nWhat the plots do establish is heterogeneity. The probability of a zero changes with observed patient characteristics, which makes a separate zero process plausible enough to investigate. It does not yet tell us whether a zero-inflated model will outperform an overdispersed one-process model.\n\n### Adjusted Associations with an Observed Zero\n\nCollapsing the outcome to **zero versus one or more visits** allows an adjusted analysis of the observed zero pattern. This logistic regression is not the zero component of a fitted zero-inflated model and cannot identify which observed zeros are structural. It asks only whether the adjusted probability of recording no visits varies with the available predictors.\n\nIn applied work, I would use this step to start a conversation with domain experts. A coefficient can show that a group has more or fewer zero records after adjustment, but it cannot tell us whether those zeros arise from good health, poor access, avoidance, eligibility rules, or an omitted variable.\n\n\n::: {#tbl-logistic-analysis .cell tbl-cap='Adjusted associations with recording zero physician office visits.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show logistic model code\"}\n# Create binary indicator: 1 = zero visits, 0 = any visits\nmedcare$no_visits <- ifelse(medcare$ofp == 0, 1, 0)\n\n# Fit logistic regression\nlogistic_model <- glm(\n  no_visits ~ healthpoor + healthexcellent + numchron + age + male + married,\n  data = medcare,\n  family = binomial()\n)\n\nlogistic_table <- model_parameters(\n  logistic_model,\n  exponentiate = TRUE\n) |>\n  filter(Parameter != \"(Intercept)\") |>\n  transmute(\n    Predictor = recode(\n      Parameter,\n      healthpoor = \"Poor vs average health\",\n      healthexcellent = \"Excellent vs average health\",\n      numchron = \"Chronic conditions (per condition)\",\n      age = \"Age (per decade)\",\n      male = \"Male vs female\",\n      married = \"Married vs not married\"\n    ),\n    `Odds ratio` = sprintf(\"%.2f\", Coefficient),\n    `95% CI` = sprintf(\"%.2f–%.2f\", CI_low, CI_high),\n    `p-value` = format.pval(p, digits = 2, eps = 0.001)\n  )\n\nknitr::kable(logistic_table, align = c(\"l\", \"r\", \"c\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Predictor                          | Odds ratio|  95% CI   | p-value|\n|:----------------------------------|----------:|:---------:|-------:|\n|Poor vs average health             |       1.22| 0.89–1.65 |   0.204|\n|Excellent vs average health        |       1.24| 0.94–1.62 |   0.129|\n|Chronic conditions (per condition) |       0.58| 0.53–0.63 |  <0.001|\n|Age (per decade)                   |       0.89| 0.77–1.02 |   0.092|\n|Male vs female                     |       1.70| 1.42–2.04 |  <0.001|\n|Married vs not married             |       0.64| 0.53–0.78 |  <0.001|\n\n\n:::\n:::\n\n\n@tbl-logistic-analysis shows that each additional chronic condition is associated with 42% lower odds of recording zero visits (odds ratio 0.58, 95% CI 0.53–0.63). Men have 70% higher odds of a zero than women, while married participants have 36% lower odds than those who are not married. These estimates describe associations conditional on the other variables; they do not establish causal effects.\n\nThe health-status coefficients point towards higher adjusted odds of a zero for both poor and excellent health, but the confidence intervals include 1. The data therefore do not support a clear adjusted health-status association in this specification. Likewise, the age estimate suggests that older cohorts have slightly lower odds of a zero, but its confidence interval also includes 1.\n\nThis difference between the descriptive plot and the adjusted model is useful rather than contradictory. The plot compares health groups as observed; the regression compares people with the same included covariates. Neither analysis identifies structural zeros. \n\nTogether with the descriptive plots, this model shows that zero outcomes have structure worth modelling and that their interpretation depends on the adjustment set.\n\n## Poisson Baseline\n\nThe standard starting point for count data is a Poisson regression. Even when we expect it to fail, this model provides a useful baseline:\n\n- What relationships would a one-process count model estimate?\n- How badly does the variance assumption break?\n- How many zeros would this simpler model expect?\n\nFor this application, the important Poisson assumptions are:\n\n1. **Conditional distribution**: Given the predictors, each person's count follows a Poisson distribution.\n2. **Conditional equidispersion**: The conditional variance equals the conditional mean, $$\\text{Var}(Y_i \\mid X_i) = E(Y_i \\mid X_i)$$\n3. **Independent records**: Participants are independent after conditioning on the modelled predictors.\n4. **Comparable exposure**: Each count covers the same observation window; otherwise the model needs an exposure offset.\n\nWe will first interpret the conditional-mean estimates, then check whether the Poisson variance and zero probabilities fit the data. Unlike the logistic model, which asked whether a person recorded no visits, the Poisson model uses the entire count and asks how the average number of visits changes with the predictors. It therefore provides a baseline model for the count process.\n\n\n::: {#tbl-poisson-analysis .cell tbl-cap='Poisson regression estimates for physician office visits.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Poisson model code\"}\n# Fit Poisson model\ncount_formula <- ofp ~ healthpoor + healthexcellent + numchron +\n  age + male + married\n\npoisson_model <- glm(\n  count_formula,\n  data = medcare,\n  family = poisson()\n)\n\npoisson_table <- model_parameters(\n  poisson_model,\n  exponentiate = TRUE\n) |>\n  filter(Parameter != \"(Intercept)\") |>\n  transmute(\n    Predictor = recode(\n      Parameter,\n      healthpoor = \"Poor vs average health\",\n      healthexcellent = \"Excellent vs average health\",\n      numchron = \"Chronic conditions (per condition)\",\n      age = \"Age (per decade)\",\n      male = \"Male vs female\",\n      married = \"Married vs not married\"\n    ),\n    `Rate ratio` = sprintf(\"%.2f\", Coefficient),\n    `95% CI` = sprintf(\"%.2f–%.2f\", CI_low, CI_high),\n    `p-value` = format.pval(p, digits = 2, eps = 0.001)\n  )\n\nknitr::kable(poisson_table, align = c(\"l\", \"r\", \"c\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Predictor                          | Rate ratio|  95% CI   | p-value|\n|:----------------------------------|----------:|:---------:|-------:|\n|Poor vs average health             |       1.29| 1.25–1.33 |  <0.001|\n|Excellent vs average health        |       0.70| 0.66–0.75 |  <0.001|\n|Chronic conditions (per condition) |       1.18| 1.17–1.19 |  <0.001|\n|Age (per decade)                   |       0.95| 0.93–0.97 |  <0.001|\n|Male vs female                     |       0.90| 0.88–0.93 |  <0.001|\n|Married vs not married             |       1.00| 0.97–1.03 |    0.93|\n\n\n:::\n:::\n\n\n@tbl-poisson-analysis presents the results of the Poisson regression. As a quick reminder, a Poisson rate ratio describes a proportional difference in the expected count: the average number of visits predicted for people with the same included characteristics.\n\nHere, under the Poisson mean model, poor health is associated with a 29% higher expected visit count than average health, while excellent health is associated with a 30% lower count. Each additional chronic condition is associated with an 18% increase. Men have an expected count about 10% lower than women, and a decade of age is associated with a 5% reduction. The estimate for marital status is essentially null.\n\n## Where the Poisson Model Fails\n\nThe fitted mean structure does not establish that the Poisson distribution describes the conditional variation. The Pearson residuals provide a direct assessment of equidispersion after adjustment for the predictors.\n<!-- Instead of extracting p-value, the code below prints the value - this is not very scientific and reproducible -->\n\n::: {#tbl-poisson-overdispersion .cell tbl-cap='Pearson overdispersion diagnostic for the Poisson model.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show overdispersion diagnostic code\"}\noverdispersion_check <- check_overdispersion(poisson_model)\n\noverdispersion_table <- tibble::tibble(\n  Metric = c(\n    \"Pearson chi-squared\",\n    \"Residual degrees of freedom\",\n    \"Dispersion ratio\",\n    \"p-value\"\n  ),\n  Value = c(\n    format(\n      round(overdispersion_check$chisq_statistic),\n      big.mark = \",\"\n    ),\n    format(\n      overdispersion_check$residual_df,\n      big.mark = \",\"\n    ),\n    sprintf(\"%.2f\", overdispersion_check$dispersion_ratio),\n    \"< 0.001\"\n  )\n)\n\nknitr::kable(overdispersion_table)\n```\n\n::: {.cell-output-display}\n\n\n|Metric                      |Value   |\n|:---------------------------|:-------|\n|Pearson chi-squared         |31,664  |\n|Residual degrees of freedom |4,399   |\n|Dispersion ratio            |7.20    |\n|p-value                     |< 0.001 |\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## What is overdispersion?\n\nRemember that overdispersion occurs when the conditional variance of the observed counts exceeds the variance allowed by the model. For a Poisson model, the conditional mean and variance must be equal. A dispersion ratio substantially above 1 indicates that this assumption is inadequate.\n:::\n\nThe dispersion ratio is 7.20, well above the value of 1 expected under a Poisson model. The observed visit counts therefore vary much more than the model permits under the Poisson assumption. This overdispersion makes the model-based standard errors too small and the corresponding confidence intervals and p-values too optimistic. The rate ratios still summarize the fitted mean structure, but this means that the Poisson model does not provide reliable inference for these data.\n\nOverdispersion identifies the Poisson model as inadequate but does not identify the source of the extra variation. The next one-process candidate is therefore negative binomial regression, which relaxes equidispersion without introducing a latent extra-zero group.\n\n## Negative-Binomial Fit and Zero-Frequency Comparison\n\nThe negative binomial baseline retains `count_formula`, so it makes the same conditional comparisons as the Poisson model. Its `nbinom2` variance, $\\mu_i + \\mu_i^2/\\phi$, allows variation to increase faster than the mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_model <- glmmTMB(\n  count_formula,\n  data = medcare,\n  family = nbinom2()\n)\n```\n:::\n\n\nThe fitted dispersion parameter is $\\hat{\\phi} =$ 1.13. This finite value allows substantially more conditional variation than Poisson; the Poisson limit would require $\\phi \\to \\infty$. The model still treats every participant as arising from one count-generating process.\n\nZero prediction isolates one important consequence of the different variance assumptions. For participant $i$, the fitted Poisson probability of zero is\n\n$$P(Y_i = 0) = e^{-\\hat{\\lambda}_i}$$\n\nwhereas the fitted NB2 probability is\n\n$$P(Y_i = 0) = \\left(\\frac{\\hat{\\phi}}{\\hat{\\phi}+\\hat{\\mu}_i}\\right)^{\\hat{\\phi}}.$$\n\nSumming the person-specific probabilities gives the expected number of zero-visit records under each model.\n\n\n::: {#tbl-zero-comparison .cell tbl-cap='Zeros expected from the fitted one-process models. The data contain 683 observed zero-visit records.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show zero-frequency comparison code\"}\n# Observed zeros\nobserved_zeros <- sum(medcare$ofp == 0)\n\n# Predicted zeros from Poisson model\npoisson_pred <- predict(poisson_model, type = \"response\")\npoisson_zero_prob <- exp(-poisson_pred)  # P(Y=0) for Poisson\nexpected_zeros_poisson <- sum(poisson_zero_prob)\n\n# Predicted zeros from negative binomial model\nnb_mean <- predict(nb_model, type = \"conditional\")\nnb_dispersion <- predict(nb_model, type = \"disp\")\nnb_zero_prob <- dnbinom(0, mu = nb_mean, size = nb_dispersion)\nexpected_zeros_nb <- sum(nb_zero_prob)\n\nzero_comparison <- tibble::tibble(\n  Model = c(\"Poisson\", \"Negative binomial (NB2)\"),\n  `Expected zeros` = round(c(\n    expected_zeros_poisson,\n    expected_zeros_nb\n  )),\n  `Observed minus expected` = observed_zeros - `Expected zeros`,\n  `Expected / observed` = sprintf(\n    \"%.1f%%\",\n    100 * `Expected zeros` / observed_zeros\n  )\n)\n\nknitr::kable(\n  zero_comparison,\n  align = c(\"l\", \"r\", \"r\", \"r\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Model                   | Expected zeros| Observed minus expected| Expected / observed|\n|:-----------------------|--------------:|-----------------------:|-------------------:|\n|Poisson                 |             37|                     646|                5.4%|\n|Negative binomial (NB2) |            623|                      60|               91.2%|\n\n\n:::\n:::\n\n\nThe fitted Poisson model expects approximately 37 zero-visit records, only 5.4% of the 683 observed. NB2 expects approximately 623, or 91.2% of the observed number. Allowing extra variation within one count process therefore explains most of what initially looked like a zero surplus.\n\nThe remaining shortfall is about 60 zero records. That discrepancy keeps a separate extra-zero process under consideration, but it does not prove that such a process exists. Misspecification of the conditional mean, other forms of heterogeneity, or a different count distribution could also affect zero prediction.\n\nThe baseline analysis has therefore narrowed rather than settled the question. Poisson is too restrictive, while NB2 captures most of the dispersion and zero frequency without a latent class. Section 4 introduces the extra-zero mechanism so that its additional structure can be compared with this stronger one-process benchmark.\n\n# How Zero-Inflated Models Work\n\n## A Latent Two-Process Model\n\nUnlike the negative binomial baseline, which keeps every participant in one count process, a zero-inflated model allows either of two states to generate each observed count. For participant $i$, we introduce $S_i$ as a binary indicator of that state.\n\n- $S_i=1$ means the **extra-zero state** is active. In this state, the recorded number of visits must be zero.\n- $S_i=0$ means the **count-generating state** is active. This state can produce either zero visits or a positive number of visits.\n\nThe state is *latent* because it is not recorded in the data. When a participant has zero visits, we do not know which state generated that zero. The idea is to model the probability that an individual patient will fall under each state.\n\nThis probability may vary across patient profiles. Let $Z_i$ contain the predictors used for this part of the model, and let $\\pi_i$ be the resulting probability that participant $i$ is in the extra-zero state. We write\n\n$$\n\\begin{aligned}\nS_i \\mid Z_i &\\sim \\operatorname{Bernoulli}(\\pi_i), \\\\\nP(S_i=1\\mid Z_i) &= \\pi_i.\n\\end{aligned}\n$$\n\nIn other words, $S_i$ takes the value 1 with probability $\\pi_i$, based on the participant's zero-inflation predictors $Z_i$.\n\nNow let $Y_i$ be the observed number of visits and let $X_i$ contain the predictors used for the count component. The outcome model formalizes the two states described above:\n\n$$\n\\begin{aligned}\nY_i \\mid S_i=1 &\\equiv 0, \\\\\nY_i \\mid S_i=0,X_i &\\sim f_c(\\,\\cdot\\,;\\mu_i,\\psi).\n\\end{aligned}\n$$\n\nWhen the extra-zero state is active, by definition the number of visits must be zero. In the count-generating state, visits follow $f_c$, a count distribution with mean $\\mu_i$. The placeholder $\\psi$ represents a family-specific dispersion parameter when one is required: it is absent for Poisson and equals $\\phi$ for the NB2 model used later.\n\nIn essence, and forgetting about notation for a moment, the central idea is that the extra-zero state always produces zero, whereas the count-generating state can produce either zero or a positive count. @fig-zero-inflated-process illustrates this two-stage process.\n\n![A zero-inflated model assigns probability to a latent extra-zero state and uses a count process for observations outside that state.](zero-inflated-process.svg){#fig-zero-inflated-process fig-alt=\"A hand-drawn two-stage model diagram: a patient record enters a zero-inflation process, which can produce an extra zero or pass the record to a count process that can produce zero or one or more visits.\"}\n\nFor the Medicare data, the two components therefore ask different questions. The zero-inflation component asks which patient profiles receive a higher probability of the extra-zero state. The count component asks how expected visits change within the count-generating state.\n\n## Mixture Probabilities and Likelihood\n\nZeros are ambiguous because either latent state can produce them. Positive counts are not: they can come only from the count-generating state. This asymmetry gives the model information about both components. It estimates them jointly from all observations rather than classifying the zeros first and then fitting separate regressions.\n\nLet $f_c(k;\\mu_i,\\psi)$ denote the probability that the count component assigns to the value $k$. The possible routes are:\n\n- If $y_i=0$, the observation may come directly from the extra-zero state, with probability $\\pi_i$, or from the count-generating state producing zero, with probability $(1-\\pi_i)f_c(0;\\mu_i,\\psi)$.\n- If $y_i>0$, the observation has one possible route: the count-generating state, with probability $(1-\\pi_i)f_c(y_i;\\mu_i,\\psi)$.\n\nThe likelihood contribution $L_i$ is the probability that the model assigns to the outcome observed for participant $i$. The two cases above give\n\n$$\nL_i(\\pi_i,\\mu_i,\\psi)\n=\n\\begin{cases}\n\\pi_i+(1-\\pi_i)f_c(0;\\mu_i,\\psi), & y_i=0, \\\\\n(1-\\pi_i)f_c(y_i;\\mu_i,\\psi), & y_i>0.\n\\end{cases}\n$$\n\nIn each case, $L_i$ is the probability that the model assigns to participant $i$'s observed outcome. For a zero, the contribution adds the probabilities of both routes instead of choosing one. Across the sample, these contributions form a single objective for estimating the count, zero-inflation, and dispersion parameters together.\n\n::: {.callout-caution collapse=\"true\" title=\"The full likelihood\"}\n\nMultiplying the contributions from all $n$ participants gives the full likelihood. The coefficient vectors $\\beta$ and $\\gamma$ govern the count and zero-inflation components, respectively:\n\n$$\nL(\\beta,\\gamma,\\psi)\n=\n\\prod_{i=1}^{n}\nL_i\\bigl(\\pi_i(\\gamma),\\mu_i(\\beta),\\psi\\bigr).\n$$\n\nMaximizing this product estimates the count, zero-inflation, and dispersion parameters jointly.\n\n:::\n\nJoint estimation also explains why the preliminary logistic regression in @tbl-logistic-analysis is not the fitted zero-inflation component. The preliminary regression models the observed event $Y_i=0$, regardless of which state produced the zero. The fitted zero-inflation component models the latent event $S_i=1$. These are different outcomes: the probability of an observed zero includes both routes, whereas $\\pi_i$ is the model probability of the extra-zero state.\n\nBecause the state remains unobserved, a zero raises the practical question: given that we observed a zero, what is the probability that it came from the extra-zero state rather than from the count-generating state? The posterior probability below answers that question. Bayes' rule first expresses it in terms of model probabilities:\n\n$$\n\\begin{aligned}\nP(S_i=1\\mid Y_i=0,X_i,Z_i)\n&=\n\\frac{\nP(Y_i=0\\mid S_i=1)P(S_i=1\\mid Z_i)\n}{\nP(Y_i=0\\mid X_i,Z_i)\n} \\\\\n&=\n\\frac{\n1\\times\\pi_i\n}{\n\\pi_i+(1-\\pi_i)f_c(0;\\mu_i,\\psi)\n}.\n\\end{aligned}\n$$\n\nThe first numerator term equals one because the extra-zero state always produces zero. The prior model probability of that state is $\\pi_i$ by definition of the zero-inflation component. The denominator contains both routes to an observed zero: the extra-zero route and a zero from the count-generating state. For a positive count, the posterior probability of the extra-zero state is zero because that state cannot produce a positive value.\n\nFor a concrete example with a Poisson count component, suppose the model assigns observations with a particular covariate profile an extra-zero probability $\\pi_i=0.15$ and a count-component mean $\\lambda_i=3.2$.\n\n- Within the count-generating state, the probability of zero visits is $e^{-3.2}=0.041$, or 4.1%.\n- Combining both routes gives an overall zero probability of $0.15+0.85(0.041)=0.185$, or 18.5%.\n- If an observation with this profile equals zero, the posterior probability of the extra-zero state is $0.15/0.185\\approx0.81$, or 81%.\n\nThis posterior probability therefore updates uncertainty about the latent state. Because the count component considers zero unlikely for this profile, observing zero shifts much of the model’s probability toward the extra-zero state. This soft assignment helps estimate the two components jointly.\n\n## Mixture Mean and Variance\n\nOnce the model has estimated the extra-zero probability and the behaviour of the count-generating state, we can ask what it predicts for observed visits. Here, $\\mu_i$ is the mean of the chosen count distribution for participant $i$ within the count-generating state. Let $V_c(\\mu_i)$ denote the corresponding variance:\n\n$$\n\\begin{aligned}\nE(Y_i\\mid S_i=0,X_i) &= \\mu_i, \\\\\n\\operatorname{Var}(Y_i\\mid S_i=0,X_i) &= V_c(\\mu_i).\n\\end{aligned}\n$$\n\nIn a single-process count model, $\\mu_i$ would also be the expected observed count. In a zero-inflated model, however, the model assigns some probability to an always-zero state. We must average over both states to obtain expected observed visits.\n\nThe extra-zero state contributes zero with probability $\\pi_i$, while the count-generating state contributes an average of $\\mu_i$ with probability $1-\\pi_i$. Therefore,\n\n$$\nE(Y_i\\mid X_i,Z_i)\n=\\pi_i(0)+(1-\\pi_i)\\mu_i\n=(1-\\pi_i)\\mu_i.\n$$\n\nThis **conditional mixture mean** is conditional on the observed predictors $X_i$ and $Z_i$, but averages over the unobserved state $S_i$. It is the quantity we need when comparing expected visits across patient profiles. Reporting $\\mu_i$ instead would describe only the count-generating state and would overstate expected observed visits whenever $\\pi_i>0$.\n\nThe mean alone does not tell us how observations are distributed around that average. Two fitted distributions can predict the same expected number of visits while assigning very different probabilities to zero, moderate, and high counts. The mixture variance summarizes this spread, so it helps us judge whether the fitted distribution represents the observed pattern of visits.\n\n::: {.callout-caution collapse=\"true\" title=\"Deriving the mixture variance\"}\n\nThe [law of total variance](https://en.wikipedia.org/wiki/Law_of_total_variance) separates variation within the latent states from variation between their conditional means.\n\n**Within-state variation** is the variation that remains after fixing the latent state. The extra-zero state contributes no variance because it always produces zero. The count-generating state contributes $V_c(\\mu_i)$ and occurs with probability $1-\\pi_i$. Therefore,\n\n$$\n\\begin{gathered}\nE\\!\\left[\n\\operatorname{Var}(Y_i\\mid S_i,X_i,Z_i)\n\\right] \\\\\n=\\pi_i(0)+(1-\\pi_i)V_c(\\mu_i) \\\\\n=(1-\\pi_i)V_c(\\mu_i).\n\\end{gathered}\n$$\n\n**Between-state variation** arises because the states have different means: zero in the extra-zero state and $\\mu_i$ in the count-generating state. The state-specific mean can be written as $\\mu_i(1-S_i)$. Because $S_i$ is Bernoulli with probability $\\pi_i$,\n\n$$\n\\begin{gathered}\n\\operatorname{Var}\\!\\left[\nE(Y_i\\mid S_i,X_i,Z_i)\n\\right] \\\\\n=\\mu_i^2\\operatorname{Var}(1-S_i) \\\\\n=\\pi_i(1-\\pi_i)\\mu_i^2.\n\\end{gathered}\n$$\n\nAdding the within-state and between-state contributions gives the mixture variance:\n\n$$\n\\operatorname{Var}(Y_i\\mid X_i,Z_i)\n=\n\\underbrace{(1-\\pi_i)V_c(\\mu_i)}_{\\text{within-state variation}}\n+\n\\underbrace{\\pi_i(1-\\pi_i)\\mu_i^2}_{\\text{between-state variation}}.\n$$\n\n:::\n\nThe count distribution determines $V_c(\\mu_i)$. A Poisson count state has $V_c(\\mu_i)=\\mu_i$, giving a **zero-inflated Poisson (ZIP)** model. An NB2 count state has $V_c(\\mu_i)=\\mu_i+\\mu_i^2/\\phi$, giving a **zero-inflated negative-binomial (ZINB)** model. The resulting mixture variances are shown below.\n\n::: {#tbl-zero-inflated-moments .responsive}\n\n| Model | Count-state zero probability $f_c(0)$ | Count-state variance $V_c(\\mu_i)$ | Conditional mixture variance |\n|:--|:--|:--|:--|\n| ZIP | $e^{-\\mu_i}$ | $\\mu_i$ | $(1-\\pi_i)\\mu_i+\\pi_i(1-\\pi_i)\\mu_i^2$ |\n| ZINB (NB2) | $\\left(\\dfrac{\\phi}{\\phi+\\mu_i}\\right)^\\phi$ | $\\mu_i+\\dfrac{\\mu_i^2}{\\phi}$ | $(1-\\pi_i)\\left(\\mu_i+\\dfrac{\\mu_i^2}{\\phi}\\right)+\\pi_i(1-\\pi_i)\\mu_i^2$ |\n\nCount-component probabilities and resulting mixture variances for ZIP and ZINB.\n:::\n\nBoth models have conditional mixture mean $(1-\\pi_i)\\mu_i$. Their difference lies in the spread around that mean. ZIP uses a Poisson count state, whereas ZINB adds the term $\\mu_i^2/\\phi$ and therefore allows overdispersion within the count-generating state. As $\\phi\\to\\infty$, that additional variation disappears and the ZINB expressions approach their ZIP counterparts.\n\nFor the Medicare case study, the mean identity tells us how to calculate expected observed visits, while the variance distinguishes what each count distribution can represent. The next section connects $\\pi_i$ and $\\mu_i$ to predictors and asks how changes in either component affect the overall mean.\n\n## Regression and Overall Effects\n\nWe have seen that the overall mean depends on both the count-state mean $\\mu_i$ and the extra-zero probability $\\pi_i$. The next question is then: how does a predictor change that mean?\n\nIn a zero-inflated model, a predictor may change expected visits within the count-generating state, the probability of the extra-zero state, or both. Its component coefficient therefore need not describe its association with observed visits.\n\nLet $X_i$ contain the count-component predictors and let $\\beta$ contain their coefficients. Let $Z_i$ contain the zero-inflation predictors and let $\\gamma$ contain their coefficients. In `glmmTMB`, the zero-inflation component always uses a logit link. The count-component link is more flexible: the log link is the default for the Poisson and NB2 distributions used here, as it is for most count distributions available in `glmmTMB`, but it can be changed. The models in this tutorial therefore use\n\n$$\n\\begin{aligned}\n\\log(\\mu_i) &= X_i\\beta, \\\\\n\\operatorname{logit}(\\pi_i) &= Z_i\\gamma.\n\\end{aligned}\n$$\n\nThe log link keeps $\\mu_i$ positive, while the logit link keeps $\\pi_i$ between zero and one. A predictor may appear in either equation or in both.\n\n**Count component**: For a predictor $x_j$ in $X_i$, $e^{\\beta_j}$ is the rate ratio for a one-unit increase in $x_j$, holding the other count-component predictors fixed. It describes how $\\mu_i$ changes within the count-generating state.\n\n**Zero-inflation component**: For a predictor $x_j$ in $Z_i$, $e^{\\gamma_j}$ is the odds ratio for the extra-zero state. A value above one means that a one-unit increase in $x_j$ raises the modelled odds of that state, holding the other zero-inflation predictors fixed.\n\nNeither coefficient alone answers the practical question: how do expected observed visits change? That quantity still requires both components, which as we have seen in the previous section, is given by:\n\n$$\nm_i\n=E(Y_i\\mid X_i,Z_i)\n=(1-\\pi_i)\\mu_i.\n$$\n\nIn essence, the two pathways can reinforce or offset one another. Suppose a one-unit increase in a predictor raises $\\mu_i$ from 4 to 5 but also raises $\\pi_i$ from 0.10 to 0.30. The count-state mean increases by 25%, yet the overall mean falls slightly, from $(1-0.10)4=3.6$ to $(1-0.30)5=3.5$. The higher extra-zero probability more than offsets the higher count-state mean. If $\\mu_i$ rises while $\\pi_i$ falls, the two pathways instead reinforce one another.\n\n::: {.callout-caution collapse=\"true\" title=\"Combining both pathways\"}\n\nFor the additive linear predictors used here, suppose $x_j$ appears in both components. A one-unit increase gives the overall expected-count ratio\n\n$$\n\\frac{m_i(x_j+1)}{m_i(x_j)}\n=\n\\underbrace{e^{\\beta_j}}_{\\text{count-state change}}\n\\underbrace{\n\\frac{1-\\pi_i(x_j+1)}{1-\\pi_i(x_j)}\n}_{\\text{count-state probability change}}.\n$$\n\nThe first factor is the change in the count-state mean. The second is the change in the probability of being in the count-generating state. If $x_j$ appears only in the count component, the second factor equals one. If it appears only in the zero-inflation component, the first factor equals one.\n\nUnlike the count-state factor $e^{\\beta_j}$, the second factor depends on the starting value of $\\pi_i$. The combined ratio can therefore vary across patient profiles.\n\n:::\n\nBecause the pathways can reinforce or offset one another, component coefficient tables do not show how expected observed visits change. [Section 5](#fitting-checking-and-interpreting-the-models) therefore uses response-scale predictions of $m_i$ rather than stopping at rate ratios and odds ratios. Before fitting those models, however, we must decide which predictors belong in each component.\n\n## Choosing Predictors\n\nAs we have seen in the previous section, placing a variable in one formula but not the other restricts which part of the outcome distribution it may change, and as such is an important choice to make.\n\nThe two components pose different questions:\n\n1. Which variables describe visit intensity within the count-generating state?\n2. Which variables plausibly describe the probability of the extra-zero state?\n\nThe count component retains the baseline adjustment set used in the Poisson analysis:\n\n```r\nofp ~ healthpoor + healthexcellent + numchron + age + male + married\n```\n\nThese predictors represent health need and demographic differences that may be associated with visit rates. Their inclusion defines the conditional comparison; it does not turn the resulting coefficients into causal effects.\n\nIdeally, the zero-inflation formula would include direct measures of why someone cannot or does not enter the visit-generating process, such as eligibility restrictions, insurance coverage, or geographic access. The `medcare` data unfortunately contain no such measures. Its health and demographic variables can describe systematic differences in the estimated extra-zero probability, but they cannot identify the mechanism behind those differences.\n\nFor the initial ZIP and ZINB comparison, the zero-inflation component uses the more compact formula:\n\n```r\n~ numchron + male + married\n```\n\nChronic conditions, sex, and marital status showed the clearest adjusted associations with an **observed zero** in @tbl-logistic-analysis. That result provides an empirical starting point, but it's not a direct measurement of extra-zero membership: as established in the mixture-probability subsection, observed zeros combine both possible routes to zero.\n\nThese three predictors therefore enter both components initially, allowing each to be associated with visit intensity and with the estimated extra-zero probability. Including or excluding a predictor imposes a substantive restriction, and the available variables provide only indirect support for either choice. In the next section we will therefore also compare some alternative zero-inflation specifications.\n\n# Fitting, Checking, and Interpreting the Models\n\n[The predictor-selection discussion](#choosing-predictors) showed that predictor placement changes what a zero-inflated model represents: the count formula governs $\\mu_i$, while the zero formula governs $\\pi_i$. Model comparison must therefore distinguish the count distribution from the presence and specification of the extra-zero component. We will address three decisions in order:\n\n1. **Does the count component require NB2 rather than Poisson variation?**\n2. **After allowing NB2 variation, does the model benefit from any extra-zero component?**\n3. **If it does, should the extra-zero probability be constant or vary with patient characteristics?**\n\nEach question requires a matched contrast. Poisson and NB2 use the same count formula and no zero component. Ordinary NB2 and intercept-only ZINB use the same count formula and count family; `ziformula = ~ 1` adds one constant extra-zero probability rather than allowing it to vary across records. The intercept-only and covariate-dependent ZINBs then hold the NB2 count process fixed while changing only the zero formula.\n\nZIP remains useful for a different contrast. Comparing ZIP with the compact ZINB holds both formulas fixed and asks whether the count component still needs NB2 variation inside a zero-inflated model. ZIP can therefore show why adding an extra-zero component does not repair an inadequate Poisson count distribution. Comparing ZIP directly with ordinary NB2 would change both the count family and the zero formula, so it would not isolate evidence for an extra-zero component.\n\n## Fit Matched Candidate Specifications\n\nFor the sake of simplicity and exposition, every specification considered here uses the same count formula:\n\n```r\nofp ~ healthpoor + healthexcellent + numchron + age + male + married\n```\n\n[The Poisson baseline](#poisson-baseline) uses the Poisson family with no zero component, while [the negative-binomial baseline](#negative-binomial-fit-and-zero-frequency-comparison) uses NB2 with no zero component. This subsection adds only the candidates needed for the first comparisons:\n\n- **Compact ZIP:** Poisson count family with `~ numchron + male + married` as its zero formula.\n- **Intercept-only ZINB:** NB2 count family with `~ 1` as its zero formula.\n- **Compact ZINB:** NB2 count family with `~ numchron + male + married` as its zero formula.\n\nAdditional zero-component formulas are deferred until their rationale is introduced.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompact_zi_formula <- ~ numchron + male + married # <1>\n\n# Compact zero-inflated Poisson model\nzip_model <- glmmTMB(\n  count_formula,\n  ziformula = compact_zi_formula, # <2>\n  data = medcare,\n  family = poisson()\n)\n\n# Intercept-only zero-inflated NB2 model\nzinb_intercept_model <- glmmTMB(\n  count_formula,\n  ziformula = ~ 1, # <3>\n  data = medcare,\n  family = nbinom2()\n)\n\nzinb_compact_model <- glmmTMB(\n  count_formula,\n  ziformula = compact_zi_formula, \n  data = medcare,\n  family = nbinom2() # <4>\n)\n```\n:::\n\n\n1. The compact zero formula carries forward the clearest adjusted associations with observed zeros from @tbl-logistic-analysis.\n2. Compact ZIP and compact ZINB use the same count and zero formulas, so their contrast changes only the count distribution.\n3. With `nbinom2()`, `ziformula = ~ 1` assigns every record the same fitted probability of the latent extra-zero state. The NB2 count mean can still vary with the predictors in `count_formula`.\n4. Pairing a covariate-dependent `ziformula` with `nbinom2()` lets the extra-zero probability vary across patient characteristics while retaining NB2 variation in the count process.\n\nWe compare these specifications in matched pairs because each pair isolates one modelling decision: the count family, the addition of a constant extra-zero probability, or whether that probability varies with patient characteristics.\n\nIt's important to keep in mind that the resulting fit statistics provide relative evidence among the specifications, but they neither identify a distinct extra-zero population nor replace distributional diagnostics, which are still needed to assess whether the chosen count distribution adequately represents the data.\n\n## Separate Count-Family and Zero-Component Evidence\n\nThe fitted specifications now let us separate the three decisions posed at the start of this section. We first compare Poisson with NB2, using both the ordinary and zero-inflated versions, to choose the count family. We then return to the ordinary NB2 baseline and add the simplest possible extra-zero component before asking whether that component should vary across patient characteristics.\n\nBoth [AIC](https://en.wikipedia.org/wiki/Akaike_information_criterion) and [BIC](https://en.wikipedia.org/wiki/Bayesian_information_criterion) ask whether an improvement in likelihood is worth the additional parameters. Lower values favour a specification, but only differences among models fitted to the same observations with compatible likelihoods are meaningful. AIC emphasises expected predictive accuracy, whereas BIC is more reluctant to add parameters at this sample size, so comparing them shows how sensitive the result is to the penalty for complexity. These scores can rank the candidates considered here; the residual checks later will show whether the leading models are actually able to reproduce the data.\n\nHow large do these differences need to be? There is no universal pass-or-fail cutoff. Values that are close together indicate little separation between two specifications, whereas gaps of hundreds or thousands show a clear preference for the model with the lower value.\n\n\n::: {#tbl-model-performance .cell tbl-cap='In-sample comparison of five candidate model specifications. Lower AIC, BIC, and RMSE values indicate better fit by each criterion.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show model-comparison code\"}\nmodels <- list(\n  Poisson = poisson_model,\n  NB2 = nb_model,\n  `Compact ZIP` = zip_model,\n  `Intercept-only ZINB` = zinb_intercept_model,\n  `Compact ZINB` = zinb_compact_model\n)\n\ncomparison_table <- tibble::tibble(\n  Model = names(models),\n  AIC = vapply(models, AIC, numeric(1)),\n  BIC = vapply(models, BIC, numeric(1)),\n  RMSE = vapply(\n    models,\n    function(model) {\n      predictions <- predict(model, type = \"response\")\n      sqrt(mean((medcare$ofp - predictions)^2))\n    },\n    numeric(1)\n  )\n) |>\n  mutate(\n    across(c(AIC, BIC), ~ round(.x, 1)),\n    RMSE = round(RMSE, 3)\n  )\n\nknitr::kable(comparison_table, align = c(\"l\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Model               |     AIC|     BIC|  RMSE|\n|:-------------------|-------:|-------:|-----:|\n|Poisson             | 37093.4| 37138.1| 6.505|\n|NB2                 | 24576.1| 24627.2| 6.529|\n|Compact ZIP         | 33115.3| 33185.6| 6.488|\n|Intercept-only ZINB | 24574.4| 24631.9| 6.525|\n|Compact ZINB        | 24458.0| 24534.7| 6.496|\n\n\n:::\n:::\n\n\nWe start with the count family. Moving from Poisson to NB2 lowers AIC from 37093.4 to 24576.1 when neither model has an extra-zero component. Holding the compact zero formula fixed leads to the same conclusion: moving from ZIP to compact ZINB lowers AIC from 33115.3 to 24458.0. BIC tells the same story in both comparisons. These gaps leave little doubt that Poisson variation is too restrictive here, whether or not the model includes an extra-zero component.\n\nThe next question is whether NB2 needs an extra-zero component at all. The cleanest starting point is intercept-only ZINB: it keeps the NB2 count process unchanged and assigns every participant the same extra-zero probability. Compared with ordinary NB2, its AIC is only 1.7 points lower, while its BIC is 4.7 points higher. The small AIC gap and the reversal under BIC suggest that a constant extra-zero probability adds little to the ordinary NB2 model.\n\nWhat changes when the extra-zero probability can vary between participants? Relative to intercept-only ZINB, the compact ZINB lowers AIC by 116.4 points and BIC by 97.2 points. Both gaps are large: allowing the zero component to vary with chronic conditions, sex, and marital status improves the fitted distribution substantially. It does not, however, show that the zeros came from a separate, identifiable group of patients.\n\nThe RMSE column appears to disagree with AIC and BIC because it assesses only the predicted average. For each participant, RMSE compares the observed count with the model's expected count; it does not consider how much probability the model assigned to that count or to other possible counts. Compact ZIP therefore achieves the lowest RMSE, 6.488, even though its AIC and BIC are much higher than those of the NB2 models. Two models can predict similar averages while assigning very different probabilities to zeros, moderate counts, and unusually high counts. If prediction became a primary goal, repeated cross-validation should assess a score for the entire predictive distribution, such as held-out log predictive density or ranked probability score, alongside RMSE.\n\nThe comparison therefore narrows the next decision: retain NB2 variation in the count component, then ask which covariate-dependent zero formula, if any, provides a defensible working specification.\n\n## Choose the Zero-Component Specification\n\nThe preceding comparison showed that adding a constant extra-zero probability to NB2 changes fit very little, whereas allowing that probability to vary across participants produces a much larger improvement. That result leaves an important specification question: which participant characteristics should be allowed to change the extra-zero probability?\n\nStarting from the intercept-only ZINB, we compare three ways of allowing that probability to vary:\n\n- The excellent-health specification represents a narrow health-need explanation;\n- The compact specification carries forward the strongest adjusted associations with an observed zero in these data;\n- The shared-adjustment specification allows every count predictor to have a separate zero-component association.\n\nAll four models retain the same NB2 count family and count formula, so the comparison concerns only the zero-component specification. This small candidate set tests whether the compact model's improvement depends on its particular formula and whether the broader specification earns its additional complexity.\n\n\n::: {#tbl-zinb-specification-candidates .cell tbl-cap='Comparison of four candidate ZINB zero-component specifications. Every model uses the same NB2 count family and count formula.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ZINB specification-comparison code\"}\nzinb_spec_models <- list(\n  `Intercept-only` = zinb_intercept_model,\n  `Excellent-health only` = glmmTMB(\n    count_formula,\n    ziformula = ~ healthexcellent,\n    data = medcare,\n    family = nbinom2()\n  ),\n  Compact = zinb_compact_model,\n  `Shared adjustment set` = glmmTMB(\n    count_formula,\n    ziformula = ~ healthpoor + healthexcellent + numchron +\n      age + male + married,\n    data = medcare,\n    family = nbinom2()\n  )\n)\n\nzinb_model <- zinb_spec_models[[\"Compact\"]]\n\nzinb_spec_table <- tibble::tibble(\n  Specification = names(zinb_spec_models),\n  `Zero-inflation formula` = c(\n    \"~ 1\",\n    \"~ healthexcellent\",\n    sub(\"^~\", \"~ \", format(compact_zi_formula)),\n    \"~ healthpoor + healthexcellent + numchron + age + male + married\"\n  ),\n  `Substantive restriction` = c(\n    \"Keeps the extra-zero probability constant across participants.\",\n    \"Allows an excellent-health difference, but none by the other predictors; average and poor health share the same fitted probability.\",\n    \"Allows differences by chronic-condition count, sex, and marital status; excludes age and additional self-rated-health differences.\",\n    \"Allows each count predictor its own zero-component association; imposes the fewest restrictions at the cost of three additional coefficients.\"\n  ),\n  AIC = vapply(zinb_spec_models, AIC, numeric(1)),\n  BIC = vapply(zinb_spec_models, BIC, numeric(1))\n) |>\n  mutate(\n    across(c(AIC, BIC), ~ round(.x, 1))\n  ) |>\n  arrange(AIC)\n\nknitr::kable(zinb_spec_table, align = c(\"l\", \"l\", \"l\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Specification         |Zero-inflation formula                                           |Substantive restriction                                                                                                                       |     AIC|     BIC|\n|:---------------------|:----------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------|-------:|-------:|\n|Shared adjustment set |~ healthpoor + healthexcellent + numchron + age + male + married |Allows each count predictor its own zero-component association; imposes the fewest restrictions at the cost of three additional coefficients. | 24457.8| 24553.6|\n|Compact               |~ numchron + male + married                                      |Allows differences by chronic-condition count, sex, and marital status; excludes age and additional self-rated-health differences.            | 24458.0| 24534.7|\n|Intercept-only        |~ 1                                                              |Keeps the extra-zero probability constant across participants.                                                                                | 24574.4| 24631.9|\n|Excellent-health only |~ healthexcellent                                                |Allows an excellent-health difference, but none by the other predictors; average and poor health share the same fitted probability.           | 24576.0| 24639.9|\n\n\n:::\n:::\n\n\nThe four zero formulas are not all nested, so no single likelihood-ratio test can compare all of them. We therefore use the information-criterion framework introduced above: AIC for relative in-sample comparison and BIC as a stronger parsimony check.\n\nThe results give us little reason to carry forward the intercept-only or excellent-health-only models. As the preceding comparison showed, the intercept-only model receives little support beyond ordinary NB2. Allowing the extra-zero probability to vary only with excellent health does no better: its AIC is 24576.0 and its BIC is 24639.9, both higher than the intercept-only model's values of 24574.4 and 24631.9. A single excellent-health indicator is therefore too narrow to reproduce the improvement seen with the compact formula.\n\nThat leaves the compact and shared-adjustment specifications. The shared-adjustment model lowers AIC by only 0.2 points, from 24458.0 to 24457.8, but raises BIC by 18.9 points. I therefore keep the compact formula: the three extra coefficients in the shared-adjustment model make almost no difference to AIC and incur a much larger BIC penalty. \n\nThe compact formula was chosen partly after examining adjusted associations with an observed zero in this same dataset, and remains a provisional teaching specification.\n\nGiven the results, for the rest of the article, we carry forward `~ numchron + male + married` as the **provisional compact ZINB working specification**. The confidence intervals and p-values reported later treat this formula as if it had been fixed before the analysis. They do not account for the predictor-selection step.\n\nFinally, before relying on these comparisons, it's good practice to check whether each candidate produced a numerically trustworthy solution. A successful optimizer termination, a positive-definite Hessian, and finite standard errors indicate that the software found a well-defined optimum. Large zero-component coefficients can instead signal a nearly flat likelihood in which the extra-zero probability approaches zero or one.\n\n::: {.callout-note collapse=\"true\"}\n## Checking for estimation stability\n\nThe code below applies the same checks to every `glmmTMB` candidate used in the information-criterion comparisons. It then reports the number of flagged candidates and shows the compact ZINB as a worked example. The supplementary `diagnose()` call checks coefficient magnitudes, predictor scaling, and Hessian curvature. We disable its large-$z$ screen because a precisely estimated association is not by itself an optimization failure.\n\n\n::: {#tbl-estimation-stability .cell tbl-cap='Estimation-stability checks for the fitted candidates, with detailed results for the compact ZINB working specification.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show estimation-stability checks for the fitted candidates.\"}\ncandidate_glmmtmb_models <- c(\n  list(\n    NB2 = nb_model,\n    `Compact ZIP` = zip_model\n  ),\n  setNames(\n    zinb_spec_models,\n    paste(names(zinb_spec_models), \"ZINB\")\n  )\n)\n\ncheck_estimation_stability <- function(model) {\n  coefficient_blocks <- summary(model)$coefficients\n  standard_errors <- unlist(lapply(\n    coefficient_blocks,\n    function(block) {\n      if (is.null(block) || nrow(block) == 0) {\n        return(numeric(0))\n      }\n      block[, \"Std. Error\"]\n    }\n  ))\n  zero_coefficients <- unname(fixef(model)$zi)\n\n  # diagnose() prints a short message, so capture it while retaining its result.\n  diagnose_message <- capture.output(\n    diagnose_ok <- glmmTMB::diagnose(\n      model,\n      check_zstats = FALSE,\n      explain = FALSE\n    )\n  )\n\n  tibble::tibble(\n    optimizer_ok = model$fit$convergence == 0,\n    hessian_ok = isTRUE(model$sdr$pdHess),\n    finite_se = length(standard_errors) > 0 &&\n      all(is.finite(standard_errors)),\n    extreme_zero_coefficient = length(zero_coefficients) > 0 &&\n      any(abs(zero_coefficients) > 10),\n    diagnose_ok = isTRUE(diagnose_ok)\n  )\n}\n\nstability_checks <- dplyr::bind_rows(\n  lapply(candidate_glmmtmb_models, check_estimation_stability),\n  .id = \"Model\"\n) |>\n  mutate(\n    all_checks_pass = optimizer_ok & hessian_ok & finite_se &\n      !extreme_zero_coefficient & diagnose_ok\n  )\n\ncompact_checks <- stability_checks |>\n  filter(Model == \"Compact ZINB\")\n\nstability_status <- bind_rows(\n  tibble::tibble(\n    Scope = \"All comparison candidates\",\n    Check = \"Candidates with one or more flagged checks\",\n    Result = sprintf(\n      \"%d of %d\",\n      sum(!stability_checks$all_checks_pass),\n      nrow(stability_checks)\n    )\n  ),\n  tibble::tibble(\n    Scope = \"Compact ZINB\",\n    Check = c(\n      \"Optimizer termination\",\n      \"Positive-definite Hessian\",\n      \"Finite standard errors\",\n      \"Zero-component coefficient magnitude\",\n      \"Supplementary diagnose() checks\"\n    ),\n    Result = c(\n      ifelse(compact_checks$optimizer_ok, \"Passed\", \"Flagged\"),\n      ifelse(compact_checks$hessian_ok, \"Passed\", \"Flagged\"),\n      ifelse(compact_checks$finite_se, \"Passed\", \"Flagged\"),\n      ifelse(\n        compact_checks$extreme_zero_coefficient,\n        \"Flagged\",\n        \"No coefficient with |estimate| > 10\"\n      ),\n      ifelse(compact_checks$diagnose_ok, \"Passed\", \"Flagged\")\n    )\n  )\n)\n\nknitr::kable(stability_status, align = c(\"l\", \"l\", \"l\"))\n```\n\n::: {.cell-output-display}\n\n\n|Scope                     |Check                                      |Result                                        |\n|:-------------------------|:------------------------------------------|:---------------------------------------------|\n|All comparison candidates |Candidates with one or more flagged checks |0 of 6                                        |\n|Compact ZINB              |Optimizer termination                      |Passed                                        |\n|Compact ZINB              |Positive-definite Hessian                  |Passed                                        |\n|Compact ZINB              |Finite standard errors                     |Passed                                        |\n|Compact ZINB              |Zero-component coefficient magnitude       |No coefficient with &#124;estimate&#124; > 10 |\n|Compact ZINB              |Supplementary diagnose() checks            |Passed                                        |\n\n\n:::\n:::\n\n\n`diagnose()` is an experimental troubleshooting aid, so the explicit optimizer, Hessian, standard-error, and coefficient checks remain visible rather than being replaced by one package-generated verdict.\n:::\n\nAll six `glmmTMB` candidates passed these checks, including the compact ZINB shown above. Their likelihood comparisons and coefficient estimates therefore show no evident numerical warning.\n\n## Check Distributional Fit\n\nWe now examine how closely the compact ZINB reproduces the observed visit counts. `DHARMa` simulates outcomes from the fitted model and compares each observation with its simulated distribution. It expresses the result as a scaled residual between 0 and 1; a well-calibrated model should produce residuals that are approximately uniform across that interval.\n\n::: {.callout-caution collapse=\"true\"}\n## DHARMa's scaled residuals\n\nFor participant $i$, let $y_i$ be the observed count and let $y_i^{(1)}, \\ldots, y_i^{(S)}$ denote $S$ responses simulated from the conditional fitted distribution implied by the model. In this tutorial, that distribution is determined by the participant's covariates and the estimated ZINB parameters.\n\nDHARMa approximates the fitted cumulative distribution function at the observation by calculating the proportions of simulated responses strictly below and less than or equal to the observed value:\n\n$$\nL_i = \\frac{1}{S}\\sum_{s=1}^{S}\\mathbb{1}\\!\\left(y_i^{(s)} < y_i\\right),\n\\qquad\nU_i = \\frac{1}{S}\\sum_{s=1}^{S}\\mathbb{1}\\!\\left(y_i^{(s)} \\leq y_i\\right).\n$$\n\nHere, $\\mathbb{1}(A)$ is the indicator function: it equals 1 when statement $A$ is true and 0 otherwise. $L_i$ is the empirical cumulative distribution immediately to the left of $y_i$, while $U_i$ is its value at $y_i$. The interval from $L_i$ to $U_i$ therefore represents the fitted probability assigned to the observed count.\n\nDHARMa then draws\n\n$$\nr_i \\sim \\operatorname{Uniform}(L_i, U_i).\n$$\n\nRandomisation spreads observations tied at the same discrete count across the probability interval associated with that count. Under a correctly specified model and the conditional-independence assumption used here, these randomised residuals are approximately independent $\\operatorname{Uniform}(0,1)$ variables; the approximation reflects the finite number of simulations. The [DHARMa vignette](https://stat.ethz.ch/CRAN/web/packages/DHARMa/vignettes/DHARMa.html) develops the method and its diagnostic interpretation in more detail.\n:::\n\nThree standard checks provide the first overview:\n\n1. **Zero frequency:** Does the model reproduce the number of observed zeros?\n2. **Dispersion:** Is the observed residual spread consistent with the simulations?\n3. **Overall uniformity:** Does the fitted conditional distribution reproduce the response more broadly?\n\nWe begin with zero frequency because it was the specific weakness of the [negative-binomial model](#negative-binomial-fit-and-zero-frequency-comparison). NB remains as a benchmark for that comparison; the other diagnostics show what changes when the compact ZINB repairs the zero count. I use 1,000 simulations, rather than DHARMa's default of 250, to reduce Monte Carlo variation and support the bootstrap outlier check below. A fixed seed makes the results reproducible, and the same simulations supply every diagnostic and figure in this subsection.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show residual-simulation code\"}\nnb_residuals <- simulateResiduals(\n  fittedModel = nb_model,\n  n = 1000,\n  seed = 123,\n  plot = FALSE\n)\n\nzinb_residuals <- simulateResiduals(\n  fittedModel = zinb_model,\n  n = 1000,\n  seed = 123,\n  plot = FALSE\n)\n```\n:::\n\n\n\n::: {#tbl-candidate-diagnostic-tests .cell tbl-cap='Simulation checks for the negative-binomial benchmark and compact ZINB.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show diagnostic-test code\"}\nnb_zero_test <- testZeroInflation(nb_residuals, plot = FALSE)\nnb_dispersion_test <- testDispersion(nb_residuals, plot = FALSE)\nnb_uniformity_test <- testUniformity(nb_residuals, plot = FALSE)\n\nzinb_zero_test <- testZeroInflation(zinb_residuals, plot = FALSE)\nzinb_dispersion_test <- testDispersion(zinb_residuals, plot = FALSE)\nzinb_uniformity_test <- testUniformity(zinb_residuals, plot = FALSE)\n\nformat_diagnostic <- function(statistic, p_value, digits = 2) {\n  p_text <- format.pval(p_value, digits = 2, eps = 0.001)\n  p_text <- if (startsWith(p_text, \"<\")) {\n    sub(\"<\", \"< \", p_text, fixed = TRUE)\n  } else {\n    paste(\"=\", p_text)\n  }\n\n  sprintf(paste0(\"%.\", digits, \"f (p %s)\"), statistic, p_text)\n}\n\ndiagnostic_table <- tibble::tibble(\n  Check = c(\"Zero frequency\", \"Dispersion\", \"Overall uniformity\"),\n  `Statistic shown` = c(\n    \"Observed/simulated zeros\",\n    \"Observed/simulated spread\",\n    \"KS D (uniformity)\"\n  ),\n  `Negative binomial` = c(\n    format_diagnostic(nb_zero_test$statistic, nb_zero_test$p.value),\n    format_diagnostic(\n      nb_dispersion_test$statistic,\n      nb_dispersion_test$p.value\n    ),\n    format_diagnostic(\n      nb_uniformity_test$statistic,\n      nb_uniformity_test$p.value,\n      digits = 3\n    )\n  ),\n  `Compact ZINB` = c(\n    format_diagnostic(zinb_zero_test$statistic, zinb_zero_test$p.value),\n    format_diagnostic(\n      zinb_dispersion_test$statistic,\n      zinb_dispersion_test$p.value\n    ),\n    format_diagnostic(\n      zinb_uniformity_test$statistic,\n      zinb_uniformity_test$p.value,\n      digits = 3\n    )\n  )\n)\n\nknitr::kable(diagnostic_table, align = c(\"l\", \"l\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Check              |Statistic shown           | Negative binomial|       Compact ZINB|\n|:------------------|:-------------------------|-----------------:|------------------:|\n|Zero frequency     |Observed/simulated zeros  |  1.10 (p = 0.008)|    0.97 (p = 0.27)|\n|Dispersion         |Observed/simulated spread |    1.06 (p = 0.3)|   1.18 (p = 0.002)|\n|Overall uniformity |KS D (uniformity)         | 0.024 (p = 0.014)| 0.029 (p = 0.0013)|\n\n\n:::\n:::\n\n\nThe zero-frequency row returns to the discrepancy that motivated the ZINB. The negative-binomial model produces too few zeros: the observed number is 1.10 times its simulated expectation ($p = 0.008$). For the compact ZINB, the ratio falls to 0.97 ($p = 0.27$). The extra-zero component therefore brings the overall number of zeros into line with the simulations. The remaining rows broaden the assessment to residual spread and the full residual distribution.\n\nThe dispersion row reverses the comparison. NB's ratio of 1.06 is consistent with its simulations, whereas the ZINB ratio is 1.18 ($p = 0.002$). The ZINB residual spread differs from its simulated expectation by about 18%, a noticeable as well as statistically significant departure.\n\nBoth models also depart from uniformity. The Kolmogorov--Smirnov (KS) statistic $D$ is the largest vertical gap between the empirical cumulative distribution of the residuals and the uniform reference distribution. For the compact ZINB, $D = 0.029$ corresponds to a maximum gap of 2.9 percentage points. Its $p$-value of 0.0013 is the probability, under uniform residuals, of obtaining a maximum gap at least this large. The zero component repairs the zero frequency, while the dispersion and uniformity results identify broader discrepancies to investigate.\n\nThe standard DHARMa display in @fig-zinb-diagnostics brings these results together. The left panel is a uniform QQ plot: residuals from a calibrated model should follow the diagonal. The accompanying labels report the KS uniformity, dispersion, and outlier checks; of these, the KS test corresponds directly to the QQ comparison.\n\nIn the right panel, I replace DHARMa's default quantile regressions with a single smooth line showing how the average residual changes across rank-transformed fitted values. The line should remain close to 0.5 throughout. A red star marks an observation whose count falls below every simulated value or above every simulated value for that participant. The later covariate plots follow the 25th, 50th, and 75th residual quantiles separately.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show overall residual-plot code\"}\nplot(\n  zinb_residuals,\n  quantreg = FALSE\n)\n```\n\n::: {.cell-output-display}\n![Overall simulated-residual diagnostics for the compact ZINB. The QQ comparison is close to the diagonal but statistically non-uniform; residuals against fitted values remain broadly centred while some observed counts fall beyond all values simulated for the same participant.](index_files/figure-html/fig-zinb-diagnostics-1.png){#fig-zinb-diagnostics fig-alt='Two DHARMa panels for compact ZINB. The left compares observed residual quantiles with expected uniform quantiles and reports significant uniformity, dispersion, and outlier checks. The right shows scaled residual points against rank-transformed predictions. A black smoother stays near one-half but bends slightly at the ends, and observations outside the range of all their simulated values are marked with red stars.' width=960}\n:::\n:::\n\n\nThe QQ curve lies close to the diagonal, and the right-panel smoother stays near 0.5 through most of the fitted range. Across the 4,406 observations, the diagnostic statistics pick up small but consistent departures. The next checks trace those departures through the observed count frequencies and covariates.\n\n::: {.callout-note collapse=\"true\"}\n## Bootstrap outlier check\n\nDHARMa calls an observation a simulation outlier when its observed count falls below or above every value simulated for that participant. Some such cases arise even under a well-fitting model, and their expected frequency depends on the number of simulations. For integer outcomes, the simple theoretical approximation can be inaccurate, so the bootstrap applies the same outside-the-simulated-range rule to data generated under the fitted model.\n\nThe [`testOutliers()` reference](https://stat.ethz.ch/CRAN/web/packages/DHARMa/refman/DHARMa.html#testOutliers) recommends at least 1,000 simulations and 1,000 bootstrap replicates for integer-valued outcomes. Here the bootstrap estimates how often observations should fall beyond all their simulated values and compares that expectation with the observed frequency.\n\n\n::: {#tbl-zinb-outlier-bootstrap .cell tbl-cap='Bootstrap check of observations beyond the simulated range for the compact ZINB.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show bootstrap outlier-test code\"}\nzinb_outlier_test <- testOutliers(\n  zinb_residuals,\n  type = \"bootstrap\",\n  nBoot = 1000,\n  plot = FALSE\n)\n\noutlier_table <- tibble::tibble(\n  Quantity = c(\n    \"Observed counts beyond all simulated values\",\n    \"Expected 95% frequency range under the fitted model\",\n    \"Bootstrap comparison\"\n  ),\n  Result = c(\n    sprintf(\n      \"%d of %s (%.2f%%)\",\n      unname(zinb_outlier_test$statistic),\n      format(\n        unname(zinb_outlier_test$parameter),\n        big.mark = \",\",\n        scientific = FALSE\n      ),\n      100 * unname(zinb_outlier_test$estimate)\n    ),\n    sprintf(\n      \"%.2f%%–%.2f%%\",\n      100 * unname(zinb_outlier_test$conf.int[1]),\n      100 * unname(zinb_outlier_test$conf.int[2])\n    ),\n    paste(\n      \"p\",\n      if (zinb_outlier_test$p.value < 0.001) {\n        \"< 0.001\"\n      } else {\n        paste(\"=\", format.pval(zinb_outlier_test$p.value, digits = 2))\n      }\n    )\n  )\n)\n\nknitr::kable(outlier_table, align = c(\"l\", \"l\"))\n```\n\n::: {.cell-output-display}\n\n\n|Quantity                                            |Result              |\n|:---------------------------------------------------|:-------------------|\n|Observed counts beyond all simulated values         |20 of 4,406 (0.45%) |\n|Expected 95% frequency range under the fitted model |0.05%–0.25%         |\n|Bootstrap comparison                                |p < 0.001           |\n\n\n:::\n:::\n\n\nThe compact ZINB produces 20 observations beyond the simulated range, compared with the much lower frequency expected under the fitted model. This result can arise from misspecified tails, unusual but valid observations, or data errors; the test does not distinguish among them. Individual records should be removed only when an independent data-quality check shows that they are invalid. Otherwise, they remain part of the evidence used to refine the model.\n:::\n\nWe next return from scaled residuals to the visit counts themselves. @fig-count-frequency-check compares the observed frequency of each count with the range generated by the same simulations, using the earlier NB model as a benchmark.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show count-frequency check code\"}\nsummarise_count_frequencies <- function(residuals, model_name) {\n  simulated <- residuals$simulatedResponse\n  observed <- medcare$ofp\n  displayed_counts <- 0:15\n  count_labels <- c(as.character(displayed_counts), \"16+\")\n\n  simulated_counts <- c(\n    lapply(displayed_counts, function(value) {\n      colSums(simulated == value)\n    }),\n    list(colSums(simulated >= 16))\n  )\n\n  tibble::tibble(\n    Model = model_name,\n    Count = factor(count_labels, levels = count_labels),\n    Observed = c(\n      vapply(\n        displayed_counts,\n        function(value) sum(observed == value),\n        numeric(1)\n      ),\n      sum(observed >= 16)\n    ),\n    `Simulated median` = vapply(\n      simulated_counts,\n      median,\n      numeric(1)\n    ),\n    Lower = vapply(\n      simulated_counts,\n      quantile,\n      numeric(1),\n      probs = 0.025,\n      names = FALSE\n    ),\n    Upper = vapply(\n      simulated_counts,\n      quantile,\n      numeric(1),\n      probs = 0.975,\n      names = FALSE\n    )\n  )\n}\n\ncount_frequency_check <- bind_rows(\n  summarise_count_frequencies(\n    nb_residuals,\n    \"Negative-binomial benchmark\"\n  ),\n  summarise_count_frequencies(\n    zinb_residuals,\n    \"Compact ZINB\"\n  )\n) |>\n  mutate(\n    Model = factor(\n      Model,\n      levels = c(\n        \"Negative-binomial benchmark\",\n        \"Compact ZINB\"\n      )\n    )\n  )\n\nggplot(count_frequency_check, aes(x = Count)) +\n  geom_linerange(\n    aes(\n      ymin = Lower,\n      ymax = Upper,\n      colour = \"95% simulation interval\"\n    ),\n    linewidth = 0.8\n  ) +\n  geom_point(\n    aes(y = `Simulated median`, colour = \"Simulated median\"),\n    shape = 95,\n    size = 5\n  ) +\n  geom_point(\n    aes(y = Observed, colour = \"Observed frequency\"),\n    size = 2\n  ) +\n  facet_wrap(vars(Model), ncol = 1) +\n  scale_colour_manual(\n    values = c(\n      \"95% simulation interval\" = \"#5B8DB8\",\n      \"Simulated median\" = \"#1F4E79\",\n      \"Observed frequency\" = \"#B23A33\"\n    )\n  ) +\n  labs(\n    x = \"Physician office visits\",\n    y = \"Number of participants\",\n    colour = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"bottom\",\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![Observed and simulated count frequencies under the negative-binomial benchmark and compact ZINB. Intervals contain the central 95% of frequencies across 1,000 simulated datasets; counts of 16 or more are pooled.](index_files/figure-html/fig-count-frequency-check-1.png){#fig-count-frequency-check fig-alt='Two panels compare observed visit-count frequencies with simulation intervals for negative binomial and compact ZINB. Negative binomial simulates too few zeros and too many counts of one and two. Compact ZINB aligns much more closely with the observed zero and low-count frequencies, although aggregate agreement does not remove conditional residual departures.' width=960}\n:::\n:::\n\n\nThe NB panel shows the discrepancy already identified earlier: the observed zero count lies above its simulation interval, while counts of one and two are overproduced. The compact ZINB brings the zero and low-count frequencies much closer to the data. However, this marginal agreement can still conceal conditional problems because it pools participants with different fitted distributions.\n\nTo locate those problems, @fig-zinb-continuous-residuals groups the ZINB residuals by age and chronic-condition count. A uniform residual distribution would place the three displayed quantiles on the dashed 0.25, 0.50, and 0.75 reference lines within every group.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show covariate-residual check code\"}\nage_levels <- c(\n  \"66–69\", \"70–74\", \"75–79\", \"80–84\", \"85–89\", \"90+\"\n)\nchronic_levels <- c(\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6+\")\n\nresidual_covariates <- tibble::tibble(\n  Residual = zinb_residuals$scaledResiduals,\n  `Age band` = cut(\n    round(medcare$age * 10),\n    breaks = c(65, 69, 74, 79, 84, 89, Inf),\n    labels = age_levels\n  ),\n  `Chronic conditions` = factor(\n    ifelse(medcare$numchron >= 6, \"6+\", medcare$numchron),\n    levels = chronic_levels\n  )\n)\n\nage_quantiles <- residual_covariates |>\n  group_by(`Age band`) |>\n  summarise(\n    Q25 = quantile(Residual, 0.25),\n    Median = median(Residual),\n    Q75 = quantile(Residual, 0.75),\n    .groups = \"drop\"\n  ) |>\n  rename(Level = `Age band`)\n\nchronic_quantiles <- residual_covariates |>\n  group_by(`Chronic conditions`) |>\n  summarise(\n    Q25 = quantile(Residual, 0.25),\n    Median = median(Residual),\n    Q75 = quantile(Residual, 0.75),\n    .groups = \"drop\"\n  ) |>\n  rename(Level = `Chronic conditions`)\n\nto_long_quantiles <- function(data, panel_name) {\n  bind_rows(\n    transmute(\n      data,\n      Panel = panel_name,\n      Level = as.character(Level),\n      Quantile = \"25th\",\n      Value = Q25\n    ),\n    transmute(\n      data,\n      Panel = panel_name,\n      Level = as.character(Level),\n      Quantile = \"Median\",\n      Value = Median\n    ),\n    transmute(\n      data,\n      Panel = panel_name,\n      Level = as.character(Level),\n      Quantile = \"75th\",\n      Value = Q75\n    )\n  )\n}\n\ncovariate_quantiles <- bind_rows(\n  to_long_quantiles(age_quantiles, \"Age band (years)\"),\n  to_long_quantiles(chronic_quantiles, \"Chronic conditions\")\n) |>\n  mutate(\n    Level = factor(Level, levels = c(age_levels, chronic_levels)),\n    Quantile = factor(\n      Quantile,\n      levels = c(\"25th\", \"Median\", \"75th\")\n    )\n  )\n\nggplot(\n  covariate_quantiles,\n  aes(x = Level, y = Value, colour = Quantile, group = Quantile)\n) +\n  geom_hline(\n    yintercept = c(0.25, 0.5, 0.75),\n    linetype = \"dashed\",\n    colour = \"#8A8A8A\",\n    linewidth = 0.5\n  ) +\n  geom_line(linewidth = 0.8) +\n  geom_point(size = 2) +\n  facet_wrap(vars(Panel), scales = \"free_x\", ncol = 2) +\n  scale_colour_manual(\n    values = c(\n      \"25th\" = \"#0072B2\",\n      \"Median\" = \"#222222\",\n      \"75th\" = \"#D55E00\"\n    )\n  ) +\n  scale_y_continuous(\n    limits = c(0, 1),\n    breaks = c(0, 0.25, 0.5, 0.75, 1)\n  ) +\n  labs(\n    x = NULL,\n    y = \"DHARMa scaled-residual quantile\",\n    colour = \"Within-group quantile\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"bottom\",\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![Compact-ZINB residual quantiles across age and chronic-condition groups. Dashed lines mark the 0.25, 0.50, and 0.75 quantiles expected from uniform residuals; ages 90 and older and counts of six or more are pooled because those observations are sparse.](index_files/figure-html/fig-zinb-continuous-residuals-1.png){#fig-zinb-continuous-residuals fig-alt='Two line charts show the 25th, median, and 75th DHARMa residual quantiles. Residual quantiles drift downward in the oldest age bands and vary across chronic-condition groups instead of remaining on their uniform reference lines.' width=960}\n:::\n:::\n\n\nThe age quantiles drift below their references among the oldest participants, rather than continuing the near-flat pattern implied by a single linear age term. Chronic-condition groups also vary, particularly at the low and high ends of the observed range. The plots locate the clearest departures in these parts of the data. Either the count mean, the extra-zero probability, or a combination of the two could produce the patterns.\n\nThe remaining binary predictors could hide group-specific departures or suggest an omitted interaction. @fig-zinb-group-residuals therefore compares the residual distributions across health status, sex, and marital status. For uniform residuals, each box should have a median near 0.5 and its lower and upper edges near 0.25 and 0.75.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show grouped-residual check code\"}\nhealth_status <- factor(\n  ifelse(\n    medcare$healthpoor == 1,\n    \"Poor\",\n    ifelse(medcare$healthexcellent == 1, \"Excellent\", \"Average\")\n  ),\n  levels = c(\"Average\", \"Poor\", \"Excellent\")\n)\n\ngroup_residuals <- bind_rows(\n  tibble::tibble(\n    Panel = \"Health status\",\n    Level = as.character(health_status),\n    Residual = zinb_residuals$scaledResiduals\n  ),\n  tibble::tibble(\n    Panel = \"Sex\",\n    Level = ifelse(medcare$male == 1, \"Male\", \"Female\"),\n    Residual = zinb_residuals$scaledResiduals\n  ),\n  tibble::tibble(\n    Panel = \"Marital status\",\n    Level = ifelse(\n      medcare$married == 1,\n      \"Married\",\n      \"Not married\"\n    ),\n    Residual = zinb_residuals$scaledResiduals\n  )\n) |>\n  mutate(\n    Panel = factor(\n      Panel,\n      levels = c(\"Health status\", \"Sex\", \"Marital status\")\n    ),\n    Level = factor(\n      Level,\n      levels = c(\n        \"Average\", \"Poor\", \"Excellent\",\n        \"Female\", \"Male\",\n        \"Not married\", \"Married\"\n      )\n    )\n  )\n\nggplot(group_residuals, aes(x = Level, y = Residual)) +\n  geom_hline(\n    yintercept = c(0.25, 0.5, 0.75),\n    linetype = \"dashed\",\n    colour = \"#8A8A8A\",\n    linewidth = 0.5\n  ) +\n  geom_boxplot(\n    fill = \"#D9E8F5\",\n    colour = \"#1F4E79\",\n    width = 0.62,\n    outlier.alpha = 0.15,\n    outlier.size = 0.7\n  ) +\n  facet_wrap(vars(Panel), scales = \"free_x\", ncol = 3) +\n  scale_y_continuous(\n    limits = c(0, 1),\n    breaks = c(0, 0.25, 0.5, 0.75, 1)\n  ) +\n  labs(\n    x = NULL,\n    y = \"DHARMa scaled residual\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Compact-ZINB residual distributions across health status, sex, and marital status. Dashed lines mark the quartiles expected from a uniform distribution.](index_files/figure-html/fig-zinb-group-residuals-1.png){#fig-zinb-group-residuals fig-alt='Three panels contain residual boxplots for health-status, sex, and marital-status groups. Group medians and interquartile ranges are broadly similar, with no pronounced between-group shift despite the model\\'s overall residual departures.' width=960}\n:::\n:::\n\n\nThe group distributions are broadly similar, with no particular health, sex, or marital-status interaction standing out as the next addition. The age and chronic-condition patterns offer clearer directions for further work. A fuller analysis could compare substantively motivated nonlinear terms in the count mean, the extra-zero equation, or both, and evaluate them with out-of-sample data or resampling. Adding a quadratic term chosen from these same residual plots would instead combine model development and assessment in one step.\n\nTogether, these standard checks show that the compact ZINB reproduces the overall zero and low-count frequencies much better than the negative-binomial benchmark. The remaining departures are meaningful but limited in magnitude: residual spread is about 18% above its simulated expectation, the largest uniformity gap is 2.9 percentage points, and 20 of 4,406 observations (0.45%) fall beyond all their simulated values. The age and chronic-condition plots locate further discrepancies mainly at the ends of their observed ranges. The small p-values make these patterns unlikely to be simulation noise; their absolute size and location determine how much they matter in practice.\n\nThese results support a calculated working-model choice, and for the sake of this tutorial, I retain the compact ZINB as an **illustrative working model** because it has the lowest information criteria among the fitted candidate specifications, repairs the main zero-frequency discrepancy, and directly represents the two-process question of interest. A fuller analysis would compare substantively motivated nonlinear terms, interactions, and alternative specifications, preferably with out-of-sample assessment. The next subsection interprets the fitted components while carrying these diagnostic limitations into the conclusions.\n\n## Interpret the Working ZINB Model\n\nWith ZINB selected as the working model, we can interpret its two sets of coefficients. Exponentiating the conditional coefficients gives rate ratios; exponentiating the zero-inflation coefficients gives odds ratios for membership in the extra-zero group.\n\n\n::: {#tbl-zinb-count-effects .cell tbl-cap='Count component: multiplicative effects on expected visit rates.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show count-component interpretation code\"}\ncount_df <- model_parameters(\n  zinb_model,\n  component = \"conditional\",\n  effects = \"fixed\",\n  exponentiate = TRUE\n) |>\n  filter(Parameter != \"(Intercept)\") |>\n  transmute(\n    Predictor = recode(\n      Parameter,\n      healthpoor = \"Poor vs average health\",\n      healthexcellent = \"Excellent vs average health\",\n      numchron = \"Chronic conditions (per condition)\",\n      age = \"Age (per decade)\",\n      male = \"Male vs female\",\n      married = \"Married vs not married\"\n    ),\n    `Rate ratio` = sprintf(\"%.2f\", Coefficient),\n    `95% CI` = sprintf(\"%.2f–%.2f\", CI_low, CI_high),\n    `p-value` = format.pval(p, digits = 2, eps = 0.001)\n  )\n\nknitr::kable(count_df, align = c(\"l\", \"r\", \"c\", \"r\"), row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Predictor                          | Rate ratio|  95% CI   | p-value|\n|:----------------------------------|----------:|:---------:|-------:|\n|Poor vs average health             |       1.32| 1.21–1.44 |  <0.001|\n|Excellent vs average health        |       0.73| 0.65–0.82 |  <0.001|\n|Chronic conditions (per condition) |       1.16| 1.14–1.19 |  <0.001|\n|Age (per decade)                   |       0.95| 0.90–0.99 |   0.027|\n|Male vs female                     |       0.98| 0.91–1.05 |   0.485|\n|Married vs not married             |       0.94| 0.87–1.01 |   0.077|\n\n\n:::\n:::\n\n\n\n::: {#tbl-zinb-zero-effects .cell tbl-cap='Zero-inflation component: odds ratios for belonging to the extra-zero group.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show zero-inflation-component interpretation code\"}\nzi_df <- model_parameters(\n  zinb_model,\n  component = \"zero_inflated\",\n  effects = \"fixed\",\n  exponentiate = TRUE\n) |>\n  filter(Parameter != \"(Intercept)\") |>\n  transmute(\n    Predictor = recode(\n      Parameter,\n      healthpoor = \"Poor vs average health\",\n      healthexcellent = \"Excellent vs average health\",\n      numchron = \"Chronic conditions (per condition)\",\n      age = \"Age (per decade)\",\n      male = \"Male vs female\",\n      married = \"Married vs not married\"\n    ),\n    `Odds ratio` = sprintf(\"%.2f\", Coefficient),\n    `95% CI` = sprintf(\"%.2f–%.2f\", CI_low, CI_high),\n    `p-value` = format.pval(p, digits = 2, eps = 0.001)\n  )\n\nknitr::kable(zi_df, align = c(\"l\", \"r\", \"c\", \"r\"), row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Predictor                          | Odds ratio|  95% CI   | p-value|\n|:----------------------------------|----------:|:---------:|-------:|\n|Chronic conditions (per condition) |       0.28| 0.19–0.41 |  <0.001|\n|Male vs female                     |       3.08| 1.84–5.16 |  <0.001|\n|Married vs not married             |       0.35| 0.21–0.59 |  <0.001|\n\n\n:::\n:::\n\n\nI read the fitted ZINB model in two passes.\n**First, the count component:** within the count-generating group, what changes the expected visit rate?\n\n- **Chronic conditions:** Each additional condition is associated with a 16% higher visit rate (rate ratio 1.16, 95% CI 1.14–1.19).\n- **Poor health:** Poor rather than average health is associated with a 32% higher visit rate (1.32, 95% CI 1.21–1.44).\n- **Age:** Each additional decade is associated with a 5% lower visit rate (0.95, 95% CI 0.90–0.99).\n- **Excellent health:** Excellent rather than average health is associated with a 27% lower visit rate (0.73, 95% CI 0.65–0.82).\n\nThe intervals for sex and marital status include 1, so this specification does not provide clear evidence of adjusted differences for those predictors in the count component.\n\n**Then, the zero-inflation component:** what changes the odds of belonging to the extra-zero group?\n\n- **Chronic conditions:** Each additional chronic condition is associated with lower odds of belonging to the extra-zero group (odds ratio 0.28, 95% CI 0.19–0.41).\n- **Sex:** Men have higher estimated odds than women (3.08, 95% CI 1.84–5.16).\n- **Marital status:** Married participants have lower estimated odds than those who are not married (0.35, 95% CI 0.21–0.59).\n\nThese estimates are descriptive rather than causal. The model associates the three selected predictors with latent extra-zero membership; it does not establish why those associations arise, nor does it reveal which individual zero observations are structural.\n\n### Overall Expected Visits\n\nThe component tables answer two useful but partial questions. The count table describes $\\mu_i$ within the count-generating state, while the zero-inflation table describes $\\pi_i$. Expected visits on the observed response scale combine them as $(1-\\pi_i)\\mu_i$.\n\n@tbl-zinb-overall-contrasts reports average standardized predictions for the three predictors shared by both components. For each contrast, the focal predictor is changed for every eligible participant while all other predictors retain their observed values; the response-scale predictions are then averaged. The chronic-condition contrast excludes the three participants already at the observed maximum of eight conditions, avoiding extrapolation beyond the data.\n\n\n::: {#tbl-zinb-overall-contrasts .cell tbl-cap='Average standardized overall expected visits from the working ZINB model. Values are model-based point predictions marginal over the latent state.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show standardized-prediction code\"}\naverage_response_prediction <- function(newdata) {\n  mean(predict(zinb_model, newdata = newdata, type = \"response\"))\n}\n\nchronic_reference <- medcare |>\n  filter(numchron < max(numchron))\nchronic_comparison <- chronic_reference |>\n  mutate(numchron = numchron + 1)\n\nfemale_scenario <- medcare |>\n  mutate(male = 0)\nmale_scenario <- medcare |>\n  mutate(male = 1)\nnot_married_scenario <- medcare |>\n  mutate(married = 0)\nmarried_scenario <- medcare |>\n  mutate(married = 1)\n\noverall_contrasts <- tibble::tibble(\n  Contrast = c(\n    \"One more vs observed chronic-condition count\",\n    \"Male vs female\",\n    \"Married vs not married\"\n  ),\n  Reference = c(\n    average_response_prediction(chronic_reference),\n    average_response_prediction(female_scenario),\n    average_response_prediction(not_married_scenario)\n  ),\n  Comparison = c(\n    average_response_prediction(chronic_comparison),\n    average_response_prediction(male_scenario),\n    average_response_prediction(married_scenario)\n  )\n) |>\n  mutate(\n    Difference = Comparison - Reference,\n    Ratio = Comparison / Reference\n  ) |>\n  transmute(\n    Contrast,\n    `Reference mean` = sprintf(\"%.2f\", Reference),\n    `Comparison mean` = sprintf(\"%.2f\", Comparison),\n    Difference = sprintf(\"%+.2f\", Difference),\n    Ratio = sprintf(\"%.2f\", Ratio)\n  )\n\nknitr::kable(overall_contrasts, align = c(\"l\", \"r\", \"r\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Contrast                                     | Reference mean| Comparison mean| Difference| Ratio|\n|:--------------------------------------------|--------------:|---------------:|----------:|-----:|\n|One more vs observed chronic-condition count |           5.79|            6.97|      +1.18|  1.20|\n|Male vs female                               |           5.96|            5.50|      -0.45|  0.92|\n|Married vs not married                       |           5.81|            5.73|      -0.09|  0.98|\n\n\n:::\n:::\n\n\nThese predictions show how the two components combine. Each additional chronic condition raises the count-state mean and lowers the estimated probability of the extra-zero state, so both pathways increase overall expected visits. The count-component estimate for sex is close to one, but men's higher estimated extra-zero probability lowers their overall expected visits relative to women. Marriage has opposing component associations: its fitted count-state mean is lower, while its estimated extra-zero probability is also lower. The two pathways nearly offset one another, leaving an overall point-prediction ratio of 0.98 for married versus not married.\n\nThe contrasts average over the observed covariate distribution instead of defining a single typical patient. They remain descriptive associations from the fitted model, not causal effects, and the point predictions do not express uncertainty about the estimated parameters.\n\n<!-- TODO: This needs to transition more into an \"end of tutorial recap\" you would find at the end of a scientific blog or end-of-chapter section of a textbook -->\n# Conclusion and Final Remarks\n\nThe Medicare data began with a clear warning sign: the fitted Poisson model expected about 37 zero-visit records, while the data contained 683. That gap justified more flexible models, but it did not by itself prove a separate structural-zero process. The negative binomial model showed why. A one-process count model with extra variation can explain much of what first looks like zero inflation.\n\nFor this tutorial, the compact ZINB is the working model I would interpret. It outperforms the other families under AIC and BIC, has essentially the same AIC as the broader ZINB specification with a lower BIC, brings the zero-frequency diagnostic closer to the observed data, and matches the two-process question that motivated the analysis. The case is not airtight. The leading candidates still leave some residual structure, and a broader analysis could test prediction on held-out data or compare additional count distributions. That tension is useful: model choice is not a trophy for the lowest information criterion, but a defensible argument across fit, diagnostics, parsimony, and the data-generating story.\n\nThe interpretation should stay modest. The count component describes expected visits among people in the count-generating group. The zero-inflation component estimates associations with latent extra-zero membership. It does not identify the cause of any individual zero, prove access barriers, or turn observed associations into causal effects.\n\n\n## A Repeatable Workflow\n\nThe order of the analysis matters more than any single metric. In my own work, I would reuse this sequence:\n\n1. **Start with theory.** Write down what might create extra zeros, what affects count intensity, and which predictors belong in each component.\n2. **Compare plausible distributions.** Hold the mean structure fixed initially, as in @tbl-model-performance, so Poisson, negative binomial, ZIP, and ZINB differ mainly in their distributional assumptions.\n3. **Assess candidate fit.** Use residual simulations and subject-matter checks to decide whether the leading models reproduce the features that matter. Do not interpret a model merely because it has the lowest AIC.\n4. **Interpret an adequate working model.** Check convergence and standard errors, then explain each component separately and preserve uncertainty about the latent extra-zero group.\n5. **Validate the full specification.** Revisit predictor choices, inspect residuals against important covariates, assess influential observations, and compare out-of-sample predictions.\n\nThe next layer of model choice is deciding when a hurdle model, alternative count distribution, or richer prediction workflow fits better. That material belongs in a separate advanced tutorial so this article can stay focused on the core zero-inflated workflow.\n\n## When to Use Each Model Type\n\nBelow is a quick reference for when to use each of the four common count-data model families. The table is not exhaustive, but it summarizes the main points from this tutorial.\n\n| Model Type | Best When | Avoid When |\n|------------|-----------|------------|\n| **Standard Poisson** | Conditional mean and variance are compatible, and zero frequency is reproduced | Residual checks show overdispersion or a zero-frequency mismatch |\n| **Negative Binomial** | Heterogeneity explains the extra variation without a separate zero process | Residual checks still show a substantial zero-frequency mismatch |\n| **Zero-Inflated Poisson** | A distinct extra-zero process is plausible and conditional counts are close to equidispersed | The conditional count process remains overdispersed |\n| **Zero-Inflated NB** | Both an extra-zero process and conditional overdispersion are plausible | A simpler negative binomial model validates equally well, or the data are zero-deflated |\n\n: Practical guide for choosing among common count-data model families. {#tbl-model-choice}\n\n## Further Reading\n\n- Zeileis, Kleiber, and Jackman provide the practical R reference for count-data models, including Poisson, negative binomial, hurdle, and zero-inflated specifications [@zeileis2008].\n- Lambert's paper is the classic zero-inflated Poisson reference [@lambert1992].\n- Mullahy's paper is the foundational reference on modified count-data models, including hurdle-style thinking [@mullahy1986].\n\n# References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}