project:
  type: website
  preview:
    port: 7921
  render:
    - "*.qmd"
    - "posts/*/index.qmd"
    - "!zero-inflated-models-tutorial.qmd"

author: "Andrea Di Francia"

website:
  title: "Andrea Di Francia"
  site-url: https://andreadifra.github.io/
  navbar:
    search: true
    left:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: journal-text
        text: Blog
        href: blog.qmd
      - icon: kanban
        text: Projects
        href: projects.qmd
    right:
      - icon: person-circle
        text: About
        href: about.qmd
      - icon: github
        href: https://github.com/andreadifra
      - icon: linkedin
        href: https://linkedin.com/in/andreadifrancia
  page-footer:
    left: |
      Website made with [Quarto](https://quarto.org), by Andrea Di Francia. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/).
    right:
      - icon: github
        href: https://github.com/andreadifra
      - icon: envelope
        href: mailto:andrea.l.difrancia@gmail.com
      - icon: linkedin
        href: https://linkedin.com/in/andreadifrancia

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    page-layout: full
    mainfont: "Atkinson Hyperlegible, sans-serif"
    monofont: "Fira Code, monospace"



